window.ACHIEVEMENTS = [
  // ==========================================
  // 1. TOTAL FISH CAUGHT (50 Achievements)
  // ==========================================
  { id: 'fish_1', name: 'First Cast', title: 'First Cast', desc: 'Catch 1 fish', icon: '🎣', requirement: 1, stat: 'totalFishCaught' },
  { id: 'fish_5', name: 'Nibbles', title: 'Nibbles', desc: 'Catch 5 fish', icon: '🐛', requirement: 5, stat: 'totalFishCaught' },
  { id: 'fish_10', name: 'Warming Up', title: 'Warming Up', desc: 'Catch 10 fish', icon: '🪣', requirement: 10, stat: 'totalFishCaught' },
  { id: 'fish_25', name: 'Weekend Fisher', title: 'Weekend Fisher', desc: 'Catch 25 fish', icon: '🧢', requirement: 25, stat: 'totalFishCaught' },
  { id: 'fish_50', name: 'Novice Angler', title: 'Novice Angler', desc: 'Catch 50 fish', icon: '🐟', requirement: 50, stat: 'totalFishCaught' },
  { id: 'fish_100', name: 'Dedicated Angler', title: 'Dedicated Angler', desc: 'Catch 100 fish', icon: '🥢', requirement: 100, stat: 'totalFishCaught' },
  { id: 'fish_150', name: 'Fish Fry', title: 'Fish Fry', desc: 'Catch 150 fish', icon: '🍳', requirement: 150, stat: 'totalFishCaught' },
  { id: 'fish_200', name: 'Hooked', title: 'Hooked', desc: 'Catch 200 fish', icon: '🪝', requirement: 200, stat: 'totalFishCaught' },
  { id: 'fish_250', name: 'Skilled Angler', title: 'Skilled Angler', desc: 'Catch 250 fish', icon: '🥉', requirement: 250, stat: 'totalFishCaught' },
  { id: 'fish_300', name: 'River Rat', title: 'River Rat', desc: 'Catch 300 fish', icon: '🐀', requirement: 300, stat: 'totalFishCaught' },
  { id: 'fish_400', name: 'Lake Local', title: 'Lake Local', desc: 'Catch 400 fish', icon: '🛶', requirement: 400, stat: 'totalFishCaught' },
  { id: 'fish_500', name: 'Proficient Fisher', title: 'Proficient Fisher', desc: 'Catch 500 fish', icon: '🥈', requirement: 500, stat: 'totalFishCaught' },
  { id: 'fish_600', name: 'Bait Master', title: 'Bait Master', desc: 'Catch 600 fish', icon: '🪱', requirement: 600, stat: 'totalFishCaught' },
  { id: 'fish_750', name: 'Seasoned Fisher', title: 'Seasoned Fisher', desc: 'Catch 750 fish', icon: '🧂', requirement: 750, stat: 'totalFishCaught' },
  { id: 'fish_1k', name: 'Master Angler', title: 'Master Angler', desc: 'Catch 1,000 fish', icon: '🥇', requirement: 1000, stat: 'totalFishCaught' },
  { id: 'fish_1_5k', name: 'Expert Angler', title: 'Expert Angler', desc: 'Catch 1,500 fish', icon: '🎖️', requirement: 1500, stat: 'totalFishCaught' },
  { id: 'fish_2k', name: 'Trophy Hunter', title: 'Trophy Hunter', desc: 'Catch 2,000 fish', icon: '🏆', requirement: 2000, stat: 'totalFishCaught' },
  { id: 'fish_2_5k', name: 'Veteran Angler', title: 'Veteran Angler', desc: 'Catch 2,500 fish', icon: '👴', requirement: 2500, stat: 'totalFishCaught' },
  { id: 'fish_3k', name: 'Reel Expert', title: 'Reel Expert', desc: 'Catch 3,000 fish', icon: '🧵', requirement: 3000, stat: 'totalFishCaught' },
  { id: 'fish_4k', name: 'Net Filler', title: 'Net Filler', desc: 'Catch 4,000 fish', icon: '🕸️', requirement: 4000, stat: 'totalFishCaught' },
  { id: 'fish_5k', name: 'Legendary Angler', title: 'Legendary Angler', desc: 'Catch 5,000 fish', icon: '🌟', requirement: 5000, stat: 'totalFishCaught' },
  { id: 'fish_7_5k', name: 'Ocean Conqueror', title: 'Ocean Conqueror', desc: 'Catch 7,500 fish', icon: '🌊', requirement: 7500, stat: 'totalFishCaught' },
  { id: 'fish_10k', name: 'Aquatic Master', title: 'Aquatic Master', desc: 'Catch 10,000 fish', icon: '🔱', requirement: 10000, stat: 'totalFishCaught' },
  { id: 'fish_15k', name: 'Deep Sea King', title: 'Deep Sea King', desc: 'Catch 15,000 fish', icon: '🤴', requirement: 15000, stat: 'totalFishCaught' },
  { id: 'fish_20k', name: 'The Trawler', title: 'The Trawler', desc: 'Catch 20,000 fish', icon: '🚢', requirement: 20000, stat: 'totalFishCaught' },
  { id: 'fish_25k', name: 'Net Master', title: 'Net Master', desc: 'Catch 25,000 fish', icon: '🏭', requirement: 25000, stat: 'totalFishCaught' },
  { id: 'fish_30k', name: 'Ecosystem', title: 'Ecosystem', desc: 'Catch 30,000 fish', icon: '🌏', requirement: 30000, stat: 'totalFishCaught' },
  { id: 'fish_40k', name: 'Marine Biologist', title: 'Marine Biologist', desc: 'Catch 40,000 fish', icon: '🔬', requirement: 40000, stat: 'totalFishCaught' },
  { id: 'fish_50k', name: 'Fisher King', title: 'the Fisher King', desc: 'Catch 50,000 fish', icon: '👑', requirement: 50000, stat: 'totalFishCaught' },
  { id: 'fish_75k', name: 'Aquatic Legend', title: 'Aquatic Legend', desc: 'Catch 75,000 fish', icon: '🧜‍♂️', requirement: 75000, stat: 'totalFishCaught' },
  { id: 'fish_100k', name: 'Century Fisher', title: 'the Century Fisher', desc: 'Catch 100,000 fish', icon: '💯', requirement: 100000, stat: 'totalFishCaught' },
  { id: 'fish_150k', name: 'Relentless', title: 'Relentless', desc: 'Catch 150,000 fish', icon: '😤', requirement: 150000, stat: 'totalFishCaught' },
  { id: 'fish_200k', name: 'Unstoppable', title: 'Unstoppable', desc: 'Catch 200,000 fish', icon: '🚆', requirement: 200000, stat: 'totalFishCaught' },
  { id: 'fish_250k', name: 'Myth of the Sea', title: 'the Myth of the Sea', desc: 'Catch 250,000 fish', icon: '🦄', requirement: 250000, stat: 'totalFishCaught' },
  { id: 'fish_300k', name: 'Tsunami', title: 'the Tsunami', desc: 'Catch 300,000 fish', icon: '🌊', requirement: 300000, stat: 'totalFishCaught' },
  { id: 'fish_400k', name: 'Ocean Demigod', title: 'Ocean Demigod', desc: 'Catch 400,000 fish', icon: '🏛️', requirement: 400000, stat: 'totalFishCaught' },
  { id: 'fish_500k', name: 'Half-Millionaire', title: 'the Half-Millionaire', desc: 'Catch 500,000 fish', icon: '🌓', requirement: 500000, stat: 'totalFishCaught' },
  { id: 'fish_600k', name: 'Sea Emperor', title: 'the Sea Emperor', desc: 'Catch 600,000 fish', icon: '🧛', requirement: 600000, stat: 'totalFishCaught' },
  { id: 'fish_700k', name: 'Leviathan Lord', title: 'the Leviathan Lord', desc: 'Catch 700,000 fish', icon: '🐋', requirement: 700000, stat: 'totalFishCaught' },
  { id: 'fish_800k', name: 'Heir of Poseidon', title: 'the Heir of Poseidon', desc: 'Catch 800,000 fish', icon: '🏄', requirement: 800000, stat: 'totalFishCaught' },
  { id: 'fish_900k', name: 'Neptune\'s Rival', desc: 'Catch 900,000 fish', icon: '🤺', requirement: 900000, stat: 'totalFishCaught' },
  { id: 'fish_1m', name: 'God of Fishing', title: 'the God of Fishing', desc: 'Catch 1,000,000 fish', icon: '🤯', requirement: 1000000, stat: 'totalFishCaught' },
  { id: 'fish_2m', name: 'Double God', title: 'Double God', desc: 'Catch 2,000,000 fish', icon: '👯', requirement: 2000000, stat: 'totalFishCaught' },
  { id: 'fish_5m', name: 'Cosmic Fisher', title: 'Cosmic Fisher', desc: 'Catch 5,000,000 fish', icon: '🌌', requirement: 5000000, stat: 'totalFishCaught' },
  { id: 'fish_10m', name: 'Universal Angler', title: 'Universal Angler', desc: 'Catch 10,000,000 fish', icon: '🪐', requirement: 10000000, stat: 'totalFishCaught' },
  { id: 'fish_25m', name: 'Reality Bender', title: 'the Reality Bender', desc: 'Catch 25,000,000 fish', icon: '🌀', requirement: 25000000, stat: 'totalFishCaught' },
  { id: 'fish_50m', name: 'Timeline Eraser', title: 'Timeline Eraser', desc: 'Catch 50,000,000 fish', icon: '⏳', requirement: 50000000, stat: 'totalFishCaught' },
  { id: 'fish_100m', name: 'The Absolute', title: 'The Absolute', desc: 'Catch 100,000,000 fish', icon: '⬛', requirement: 100000000, stat: 'totalFishCaught' },
  { id: 'fish_500m', name: 'Infinity', title: 'Infinity', desc: 'Catch 500,000,000 fish', icon: '♾️', requirement: 500000000, stat: 'totalFishCaught' },
  { id: 'fish_1b', name: 'The End', title: 'The End', desc: 'Catch 1,000,000,000 fish', icon: '🏁', requirement: 1000000000, stat: 'totalFishCaught' },

  // ==========================================
  // 2. MYTHIC FISH (15 Achievements)
  // ==========================================
  { id: 'mythic_1', name: 'Titan Slayer', title: 'Titan Slayer', desc: 'Catch 1 Mythic fish', icon: '👹', requirement: 1, stat: 'mythicsCaught' },
  { id: 'mythic_3', name: 'Mythic Tracker', title: 'Mythic Tracker', desc: 'Catch 3 Mythic fish', icon: '👣', requirement: 3, stat: 'mythicsCaught' },
  { id: 'mythic_5', name: 'Mythic Scout', title: 'Mythic Scout', desc: 'Catch 5 Mythic fish', icon: '🔭', requirement: 5, stat: 'mythicsCaught' },
  { id: 'mythic_10', name: 'Mythic Hunter', title: 'Mythic Hunter', desc: 'Catch 10 Mythic fish', icon: '🏹', requirement: 10, stat: 'mythicsCaught' },
  { id: 'mythic_25', name: 'Mythic Expert', title: 'Mythic Expert', desc: 'Catch 25 Mythic fish', icon: '🛡️', requirement: 25, stat: 'mythicsCaught' },
  { id: 'mythic_50', name: 'Mythic Master', title: 'Mythic Master', desc: 'Catch 50 Mythic fish', icon: '⚔️', requirement: 50, stat: 'mythicsCaught' },
  { id: 'mythic_100', name: 'Beast Tamer', title: 'Beast Tamer', desc: 'Catch 100 Mythic fish', icon: '🎪', requirement: 100, stat: 'mythicsCaught' },
  { id: 'mythic_250', name: 'Titan\'s Bane', desc: 'Catch 250 Mythic fish', icon: '☠️', requirement: 250, stat: 'mythicsCaught' },
  { id: 'mythic_500', name: 'Mythic Nightmare', title: 'Mythic Nightmare', desc: 'Catch 500 Mythic fish', icon: '😈', requirement: 500, stat: 'mythicsCaught' },
  { id: 'mythic_1k', name: 'God Slayer', title: 'God Slayer', desc: 'Catch 1,000 Mythic fish', icon: '🩸', requirement: 1000, stat: 'mythicsCaught' },
  { id: 'mythic_2_5k', name: 'Mythic Destroyer', title: 'Mythic Destroyer', desc: 'Catch 2,500 Mythic fish', icon: '🌋', requirement: 2500, stat: 'mythicsCaught' },
  { id: 'mythic_5k', name: 'Pantheon Crasher', title: 'Pantheon Crasher', desc: 'Catch 5,000 Mythic fish', icon: '🏛️', requirement: 5000, stat: 'mythicsCaught' },
  { id: 'mythic_10k', name: 'Mythic Extinction', title: 'Mythic Extinction', desc: 'Catch 10,000 Mythic fish', icon: '☄️', requirement: 10000, stat: 'mythicsCaught' },
  { id: 'mythic_25k', name: 'Eater of Worlds', title: 'Eater of Worlds', desc: 'Catch 25,000 Mythic fish', icon: '🌌', requirement: 25000, stat: 'mythicsCaught' },
  { id: 'mythic_50k', name: 'The New Myth', title: 'The New Myth', desc: 'Catch 50,000 Mythic fish', icon: '🛐', requirement: 50000, stat: 'mythicsCaught' },

  // ==========================================
  // 3. LEGENDARY FISH (20 Achievements)
  // ==========================================
  { id: 'leg_1', name: 'Legend Hunter', title: 'Legend Hunter', desc: 'Catch 1 Legendary fish', icon: '✨', requirement: 1, stat: 'legendariesCaught' },
  { id: 'leg_5', name: 'Legend Seeker', title: 'Legend Seeker', desc: 'Catch 5 Legendary fish', icon: '🔍', requirement: 5, stat: 'legendariesCaught' },
  { id: 'leg_10', name: 'Legend Scout', title: 'Legend Scout', desc: 'Catch 10 Legendary fish', icon: '📜', requirement: 10, stat: 'legendariesCaught' },
  { id: 'leg_25', name: 'Legendary Collector', title: 'Legendary Collector', desc: 'Catch 25 Legendary fish', icon: '💫', requirement: 25, stat: 'legendariesCaught' },
  { id: 'leg_50', name: 'Fabled Fisher', title: 'Fabled Fisher', desc: 'Catch 50 Legendary fish', icon: '🧚', requirement: 50, stat: 'legendariesCaught' },
  { id: 'leg_75', name: 'Storyteller', title: 'Storyteller', desc: 'Catch 75 Legendary fish', icon: '📖', requirement: 75, stat: 'legendariesCaught' },
  { id: 'leg_100', name: 'Legendary Hoarder', title: 'Legendary Hoarder', desc: 'Catch 100 Legendary fish', icon: '📦', requirement: 100, stat: 'legendariesCaught' },
  { id: 'leg_250', name: 'Epic Angler', title: 'Epic Angler', desc: 'Catch 250 Legendary fish', icon: '🎻', requirement: 250, stat: 'legendariesCaught' },
  { id: 'leg_500', name: 'Living Legend', title: 'Living Legend', desc: 'Catch 500 Legendary fish', icon: '👸', requirement: 500, stat: 'legendariesCaught' },
  { id: 'leg_750', name: 'Heroic Deeds', title: 'Heroic Deeds', desc: 'Catch 750 Legendary fish', icon: '🏰', requirement: 750, stat: 'legendariesCaught' },
  { id: 'leg_1k', name: 'Folklore Hero', title: 'Folklore Hero', desc: 'Catch 1,000 Legendary fish', icon: '🗡️', requirement: 1000, stat: 'legendariesCaught' },
  { id: 'leg_2k', name: 'Saga Writer', title: 'Saga Writer', desc: 'Catch 2,000 Legendary fish', icon: '✍️', requirement: 2000, stat: 'legendariesCaught' },
  { id: 'leg_5k', name: 'Legendary Icon', title: 'Legendary Icon', desc: 'Catch 5,000 Legendary fish', icon: '🗿', requirement: 5000, stat: 'legendariesCaught' },
  { id: 'leg_10k', name: 'Mythos Maker', title: 'Mythos Maker', desc: 'Catch 10,000 Legendary fish', icon: '🏺', requirement: 10000, stat: 'legendariesCaught' },
  { id: 'leg_20k', name: 'Legendary King', title: 'Legendary King', desc: 'Catch 20,000 Legendary fish', icon: '👑', requirement: 20000, stat: 'legendariesCaught' },
  { id: 'leg_30k', name: 'Legendary Emperor', title: 'Legendary Emperor', desc: 'Catch 30,000 Legendary fish', icon: '🎇', requirement: 30000, stat: 'legendariesCaught' },
  { id: 'leg_40k', name: 'Legendary Deity', title: 'Legendary Deity', desc: 'Catch 40,000 Legendary fish', icon: '🎆', requirement: 40000, stat: 'legendariesCaught' },
  { id: 'leg_50k', name: 'Beyond Legend', title: 'Beyond Legend', desc: 'Catch 50,000 Legendary fish', icon: '🌠', requirement: 50000, stat: 'legendariesCaught' },
  { id: 'leg_75k', name: 'Unwritten Legend', title: 'Unwritten Legend', desc: 'Catch 75,000 Legendary fish', icon: '🌫️', requirement: 75000, stat: 'legendariesCaught' },
  { id: 'leg_100k', name: 'Eternal Legend', title: 'Eternal Legend', desc: 'Catch 100,000 Legendary fish', icon: '♾️', requirement: 100000, stat: 'legendariesCaught' },

  // ==========================================
  // 4. LEVEL MILESTONES (50 Achievements)
  // ==========================================
  { id: 'lvl_5', name: 'Baby Steps', title: 'Baby Steps', desc: 'Reach level 5', icon: '👶', requirement: 5, stat: 'level' },
  { id: 'lvl_25', name: 'Newcomer', title: 'Newcomer', desc: 'Reach level 25', icon: '🛴', requirement: 25, stat: 'level' },
  { id: 'lvl_50', name: 'Getting Started', title: 'Getting Started', desc: 'Reach level 50', icon: '🚲', requirement: 50, stat: 'level' },
  { id: 'lvl_100', name: 'Apprentice', title: 'Apprentice', desc: 'Reach level 100', icon: '🎒', requirement: 100, stat: 'level' },
  { id: 'lvl_150', name: 'Journeyman', title: 'Journeyman', desc: 'Reach level 150', icon: '🚶', requirement: 150, stat: 'level' },
  { id: 'lvl_250', name: 'Rising Star', title: 'Rising Star', desc: 'Reach level 250', icon: '⭐', requirement: 250, stat: 'level' },
  { id: 'lvl_300', name: 'Professional', title: 'Professional', desc: 'Reach level 300', icon: '💼', requirement: 300, stat: 'level' },
  { id: 'lvl_350', name: 'Adept', title: 'Adept', desc: 'Reach level 350', icon: '🧢', requirement: 350, stat: 'level' },
  { id: 'lvl_400', name: 'Specialist', title: 'Specialist', desc: 'Reach level 400', icon: '🔬', requirement: 400, stat: 'level' },
  { id: 'lvl_450', name: 'Seasoned', title: 'Seasoned', desc: 'Reach level 450', icon: '🍂', requirement: 450, stat: 'level' },
  { id: 'lvl_500', name: 'Veteran', title: 'Veteran', desc: 'Reach level 500', icon: '💪', requirement: 500, stat: 'level' },
  { id: 'lvl_550', name: 'Hardened', title: 'Hardened', desc: 'Reach level 550', icon: '🛡️', requirement: 550, stat: 'level' },
  { id: 'lvl_600', name: 'Elite', title: 'Elite', desc: 'Reach level 600', icon: '🥋', requirement: 600, stat: 'level' },
  { id: 'lvl_650', name: 'Superior', title: 'Superior', desc: 'Reach level 650', icon: '🎖️', requirement: 650, stat: 'level' },
  { id: 'lvl_700', name: 'Master', title: 'Master', desc: 'Reach level 700', icon: '🧘', requirement: 700, stat: 'level' },
  { id: 'lvl_750', name: 'Grandmaster', title: 'Grandmaster', desc: 'Reach level 750', icon: '🐲', requirement: 750, stat: 'level' },
  { id: 'lvl_800', name: 'Sage', title: 'Sage', desc: 'Reach level 800', icon: '🕍', requirement: 800, stat: 'level' },
  { id: 'lvl_850', name: 'Virtuoso', title: 'Virtuoso', desc: 'Reach level 850', icon: '🎼', requirement: 850, stat: 'level' },
  { id: 'lvl_900', name: 'Champion', title: 'Champion', desc: 'Reach level 900', icon: '🥊', requirement: 900, stat: 'level' },
  { id: 'lvl_950', name: 'Hero', title: 'Hero', desc: 'Reach level 950', icon: '🦸', requirement: 950, stat: 'level' },
  { id: 'lvl_1000', name: 'Century Mark', title: 'Century Mark', desc: 'Reach level 1,000', icon: '💯', requirement: 1000, stat: 'level' },
  { id: 'lvl_1100', name: 'Overachiever I', title: 'Overachiever I', desc: 'Reach level 1,100', icon: '➕', requirement: 1100, stat: 'level' },
  { id: 'lvl_1200', name: 'Paragon', title: 'Paragon', desc: 'Reach level 1,200', icon: '💠', requirement: 1200, stat: 'level' },
  { id: 'lvl_1300', name: 'Overachiever II', title: 'Overachiever II', desc: 'Reach level 1,300', icon: '✖️', requirement: 1300, stat: 'level' },
  { id: 'lvl_1400', name: 'Ascended', title: 'Ascended', desc: 'Reach level 1,400', icon: '🕊️', requirement: 1400, stat: 'level' },
  { id: 'lvl_1500', name: 'Demigod I', title: 'Demigod I', desc: 'Reach level 1,500', icon: '⚡', requirement: 1500, stat: 'level' },
  { id: 'lvl_1750', name: 'Demigod II', title: 'Demigod II', desc: 'Reach level 1,50', icon: '🌩️', requirement: 1750, stat: 'level' },
  { id: 'lvl_2000', name: 'Immortal', title: 'Immortal', desc: 'Reach level 2,000', icon: '🧛', requirement: 2000, stat: 'level' },
  { id: 'lvl_2250', name: 'Ancient', title: 'Ancient', desc: 'Reach level 2,250', icon: '🏺', requirement: 2250, stat: 'level' },
  { id: 'lvl_2500', name: 'Transcendent', title: 'Transcendent', desc: 'Reach level 2,500', icon: '👁️', requirement: 2500, stat: 'level' },
  { id: 'lvl_2750', name: 'Ethereal', title: 'Ethereal', desc: 'Reach level 2,750', icon: '👻', requirement: 2750, stat: 'level' },
  { id: 'lvl_3000', name: 'Omnipotent', title: 'Omnipotent', desc: 'Reach level 3,000', icon: '🌠', requirement: 3000, stat: 'level' },
  { id: 'lvl_3500', name: 'Celestial', title: 'Celestial', desc: 'Reach level 3,500', icon: '🌌', requirement: 3500, stat: 'level' },
  { id: 'lvl_4000', name: 'Universal', title: 'Universal', desc: 'Reach level 4,000', icon: '🪐', requirement: 4000, stat: 'level' },
  { id: 'lvl_4500', name: 'Multiversal', title: 'Multiversal', desc: 'Reach level 4,500', icon: '🔭', requirement: 4500, stat: 'level' },
  { id: 'lvl_5000', name: 'Half-Millennium', title: 'Half-Millennium', desc: 'Reach level 5,000', icon: '🌗', requirement: 5000, stat: 'level' },
  { id: 'lvl_6000', name: 'Time Walker', title: 'Time Walker', desc: 'Reach level 6,000', icon: '⌛', requirement: 6000, stat: 'level' },
  { id: 'lvl_7000', name: 'Reality Breaker', title: 'Reality Breaker', desc: 'Reach level 7,000', icon: '🔨', requirement: 7000, stat: 'level' },
  { id: 'lvl_8000', name: 'Dimensional Lord', title: 'Dimensional Lord', desc: 'Reach level 8,000', icon: '🚪', requirement: 8000, stat: 'level' },
  { id: 'lvl_9000', name: 'Pre-Millennium', title: 'Pre-Millennium', desc: 'Reach level 9,000', icon: '🌒', requirement: 9000, stat: 'level' },
  { id: 'lvl_10000', name: 'The Millennium', title: 'The Millennium', desc: 'Reach level 10,000', icon: '👑', requirement: 10000, stat: 'level' },
  { id: 'lvl_12500', name: 'High Lord', title: 'High Lord', desc: 'Reach level 12,500', icon: '👔', requirement: 12500, stat: 'level' },
  { id: 'lvl_15000', name: 'Overlord', title: 'Overlord', desc: 'Reach level 15,000', icon: '👿', requirement: 15000, stat: 'level' },
  { id: 'lvl_20000', name: 'Emperor', title: 'Emperor', desc: 'Reach level 20,000', icon: '🏯', requirement: 20000, stat: 'level' },
  { id: 'lvl_30000', name: 'Deity', title: 'Deity', desc: 'Reach level 30,000', icon: '🛐', requirement: 30000, stat: 'level' },
  { id: 'lvl_40000', name: 'Creator', title: 'Creator', desc: 'Reach level 40,000', icon: '🎨', requirement: 40000, stat: 'level' },
  { id: 'lvl_50000', name: 'Destroyer', title: 'Destroyer', desc: 'Reach level 50,000', icon: '💣', requirement: 50000, stat: 'level' },
  { id: 'lvl_75000', name: 'The Alpha', title: 'The Alpha', desc: 'Reach level 75,000', icon: '🅰️', requirement: 75000, stat: 'level' },
  { id: 'lvl_100000', name: 'The Omega', title: 'The Omega', desc: 'Reach level 100,000', icon: 'Ω', requirement: 100000, stat: 'level' },

  // ==========================================
  // 5. GOLD EARNED (50 Achievements)
  // ==========================================
  { id: 'gold_earn_100', name: 'Pocket Change', title: 'Pocket Change', desc: 'Earn 100 total gold', icon: '🪙', requirement: 100, stat: 'totalGoldEarned' },
  { id: 'gold_earn_500', name: 'Piggy Bank', title: 'Piggy Bank', desc: 'Earn 500 total gold', icon: '🐖', requirement: 500, stat: 'totalGoldEarned' },
  { id: 'gold_earn_1k', name: 'First Fortune', title: 'First Fortune', desc: 'Earn 1,000 total gold', icon: '💰', requirement: 1000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_2_5k', name: 'Bonus Check', title: 'Bonus Check', desc: 'Earn 2,500 total gold', icon: '✉️', requirement: 2500, stat: 'totalGoldEarned' },
  { id: 'gold_earn_5k', name: 'Small Business', title: 'Small Business', desc: 'Earn 5,000 total gold', icon: '🛖', requirement: 5000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_7_5k', name: 'Profitable', title: 'Profitable', desc: 'Earn 7,500 total gold', icon: '📈', requirement: 7500, stat: 'totalGoldEarned' },
  { id: 'gold_earn_10k', name: 'Wealthy Trader', title: 'Wealthy Trader', desc: 'Earn 10,000 total gold', icon: '💵', requirement: 10000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_15k', name: 'Making Bank', title: 'Making Bank', desc: 'Earn 15,000 total gold', icon: '🏦', requirement: 15000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_25k', name: 'Nest Egg', title: 'Nest Egg', desc: 'Earn 25,000 total gold', icon: '🥚', requirement: 25000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_50k', name: 'Successful Merchant', title: 'Successful Merchant', desc: 'Earn 50,000 total gold', icon: '🏘️', requirement: 50000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_75k', name: 'Lavish', title: 'Lavish', desc: 'Earn 75,000 total gold', icon: '🥂', requirement: 75000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_100k', name: 'Gold Baron', title: 'Gold Baron', desc: 'Earn 100,000 total gold', icon: '🤴', requirement: 100000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_150k', name: 'Luxury Life', title: 'Luxury Life', desc: 'Earn 150,000 total gold', icon: '🏎️', requirement: 150000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_200k', name: 'Opulent', title: 'Opulent', desc: 'Earn 200,000 total gold', icon: '💍', requirement: 200000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_250k', name: 'Gilded Angler', title: 'Gilded Angler', desc: 'Earn 250,000 total gold', icon: '🧈', requirement: 250000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_500k', name: 'Half-Millionaire', title: 'the Half-Millionaire', desc: 'Earn 500,000 total gold', icon: '🌗', requirement: 500000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_750k', name: 'Three-Quarters', title: 'Three-Quarters', desc: 'Earn 750,000 total gold', icon: '🌖', requirement: 750000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_1m', name: 'Millionaire', title: 'Millionaire', desc: 'Earn 1,000,000 total gold', icon: '💎', requirement: 1000000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_2m', name: 'Multi-Millionaire', title: 'Multi-Millionaire', desc: 'Earn 2,000,000 total gold', icon: '🏙️', requirement: 2000000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_5m', name: 'Capitalist', title: 'Capitalist', desc: 'Earn 5,000,000 total gold', icon: '🎩', requirement: 5000000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_10m', name: 'Tycoon', title: 'Tycoon', desc: 'Earn 10,000,000 total gold', icon: '🏭', requirement: 10000000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_25m', name: 'Magnate', title: 'Magnate', desc: 'Earn 25,000,000 total gold', icon: '🚇', requirement: 25000000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_50m', name: 'Conglomerate', title: 'Conglomerate', desc: 'Earn 50,000,000 total gold', icon: '🌐', requirement: 50000000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_75m', name: 'Monopoly', title: 'Monopoly', desc: 'Earn 75,000,000 total gold', icon: '🎲', requirement: 75000000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_100m', name: 'Empire Builder', title: 'Empire Builder', desc: 'Earn 100,000,000 total gold', icon: '🏯', requirement: 100000000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_250m', name: 'Nation Wealth', title: 'Nation Wealth', desc: 'Earn 250,000,000 total gold', icon: '🏳️', requirement: 250000000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_500m', name: 'Treasury Owner', title: 'Treasury Owner', desc: 'Earn 500,000,000 total gold', icon: '🔐', requirement: 500000000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_1b', name: 'Billionaire', title: 'Billionaire', desc: 'Earn 1,000,000,000 total gold', icon: '🚀', requirement: 1000000000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_2b', name: 'Multi-Billionaire', title: 'Multi-Billionaire', desc: 'Earn 2,000,000,000 total gold', icon: '🛰️', requirement: 2000000000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_5b', name: 'Trillionaire Prep', title: 'Trillionaire Prep', desc: 'Earn 5,000,000,000 total gold', icon: '📝', requirement: 5000000000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_10b', name: 'Economic Force', title: 'Economic Force', desc: 'Earn 10,000,000,000 total gold', icon: '🌋', requirement: 10000000000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_25b', name: 'World Bank', title: 'World Bank', desc: 'Earn 25,000,000,000 total gold', icon: '🏦', requirement: 25000000000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_50b', name: 'Global Economy', title: 'Global Economy', desc: 'Earn 50,000,000,000 total gold', icon: '🌍', requirement: 50000000000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_100b', name: 'Midas Touch', title: 'Midas Touch', desc: 'Earn 100,000,000,000 total gold', icon: '🖐️', requirement: 100000000000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_250b', name: 'Golden Planet', title: 'Golden Planet', desc: 'Earn 250,000,000,000 total gold', icon: '🪐', requirement: 250000000000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_500b', name: 'Golden System', title: 'Golden System', desc: 'Earn 500,000,000,000 total gold', icon: '☀️', requirement: 500000000000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_1t', name: 'Trillionaire', title: 'Trillionaire', desc: 'Earn 1,000,000,000,000 total gold', icon: '🌌', requirement: 1000000000000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_10t', name: 'Money Bags', title: 'Money Bags', desc: 'Earn 10T total gold', icon: '🛍️', requirement: 10000000000000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_100t', name: 'Money Pit', title: 'Money Pit', desc: 'Earn 100T total gold', icon: '🕳️', requirement: 100000000000000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_1qa', name: 'Quadrillionaire', title: 'Quadrillionaire', desc: 'Earn 1 Quadrillion total gold', icon: '1️⃣', requirement: 1000000000000000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_10qa', name: 'Infinite Wealth I', title: 'Infinite Wealth I', desc: 'Earn 10 Quadrillion total gold', icon: '♾️', requirement: 10000000000000000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_100qa', name: 'Infinite Wealth II', title: 'Infinite Wealth II', desc: 'Earn 100 Quadrillion total gold', icon: '♾️', requirement: 100000000000000000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_1qi', name: 'Quintillionaire', title: 'Quintillionaire', desc: 'Earn 1 Quintillion total gold', icon: '👑', requirement: 1000000000000000000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_10qi', name: 'Economy Breaker', title: 'Economy Breaker', desc: 'Earn 10 Quintillion total gold', icon: '📉', requirement: 10000000000000000000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_100qi', name: 'Number Overflow', title: 'Number Overflow', desc: 'Earn 100 Quintillion total gold', icon: '💾', requirement: 100000000000000000000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_1sx', name: 'Sextillionaire', title: 'Sextillionaire', desc: 'Earn 1 Sextillion total gold', icon: '🔢', requirement: 1000000000000000000000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_10sx', name: 'Money God', title: 'Money God', desc: 'Earn 10 Sextillion total gold', icon: '🛐', requirement: 10000000000000000000000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_100sx', name: 'Money Titan', title: 'Money Titan', desc: 'Earn 100 Sextillion total gold', icon: '👾', requirement: 100000000000000000000000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_1sp', name: 'Septillionaire', title: 'Septillionaire', desc: 'Earn 1 Septillion total gold', icon: '🤯', requirement: 1000000000000000000000000, stat: 'totalGoldEarned' },
  { id: 'gold_earn_max', name: 'Absolute Wealth', title: 'Absolute Wealth', desc: 'Earn 10 Septillion total gold', icon: '🔚', requirement: 10000000000000000000000000, stat: 'totalGoldEarned' },

  // ==========================================
  // 6. FISH SOLD (50 Achievements)
  // ==========================================
  { id: 'sold_1', name: 'First Sale', title: 'First Sale', desc: 'Sell 1 fish', icon: '🤝', requirement: 1, stat: 'totalFishSold' },
  { id: 'sold_5', name: 'Peddler', title: 'Peddler', desc: 'Sell 5 fish', icon: '🎒', requirement: 5, stat: 'totalFishSold' },
  { id: 'sold_10', name: 'Street Vendor', title: 'Street Vendor', desc: 'Sell 10 fish', icon: '🛣️', requirement: 10, stat: 'totalFishSold' },
  { id: 'sold_25', name: 'Market Vendor', title: 'Market Vendor', desc: 'Sell 25 fish', icon: '🪜', requirement: 25, stat: 'totalFishSold' },
  { id: 'sold_50', name: 'Stall Owner', title: 'Stall Owner', desc: 'Sell 50 fish', icon: '⛺', requirement: 50, stat: 'totalFishSold' },
  { id: 'sold_75', name: 'Shopkeeper', title: 'Shopkeeper', desc: 'Sell 75 fish', icon: '🛖', requirement: 75, stat: 'totalFishSold' },
  { id: 'sold_100', name: 'Merchant Apprentice', title: 'Merchant Apprentice', desc: 'Sell 100 fish', icon: '🏪', requirement: 100, stat: 'totalFishSold' },
  { id: 'sold_150', name: 'Regular Supplier', title: 'Regular Supplier', desc: 'Sell 150 fish', icon: '📦', requirement: 150, stat: 'totalFishSold' },
  { id: 'sold_200', name: 'Bulk Seller I', title: 'Bulk Seller I', desc: 'Sell 200 fish', icon: '📥', requirement: 200, stat: 'totalFishSold' },
  { id: 'sold_300', name: 'Bulk Seller II', title: 'Bulk Seller II', desc: 'Sell 300 fish', icon: '📤', requirement: 300, stat: 'totalFishSold' },
  { id: 'sold_400', name: 'Bulk Seller III', title: 'Bulk Seller III', desc: 'Sell 400 fish', icon: '📨', requirement: 400, stat: 'totalFishSold' },
  { id: 'sold_500', name: 'Merchant Expert', title: 'Merchant Expert', desc: 'Sell 500 fish', icon: '🛒', requirement: 500, stat: 'totalFishSold' },
  { id: 'sold_600', name: 'Wholesale Novice', title: 'Wholesale Novice', desc: 'Sell 600 fish', icon: '📜', requirement: 600, stat: 'totalFishSold' },
  { id: 'sold_750', name: 'Wholesale Expert', title: 'Wholesale Expert', desc: 'Sell 750 fish', icon: '🚛', requirement: 750, stat: 'totalFishSold' },
  { id: 'sold_1k', name: 'Supply Chain', title: 'Supply Chain', desc: 'Sell 1,000 fish', icon: '⛓️', requirement: 1000, stat: 'totalFishSold' },
  { id: 'sold_1_5k', name: 'Market Leader', title: 'Market Leader', desc: 'Sell 1,500 fish', icon: '📊', requirement: 1500, stat: 'totalFishSold' },
  { id: 'sold_2k', name: 'Distributor', title: 'Distributor', desc: 'Sell 2,000 fish', icon: '🏭', requirement: 2000, stat: 'totalFishSold' },
  { id: 'sold_2_5k', name: 'Merchant Tycoon', title: 'Merchant Tycoon', desc: 'Sell 2,500 fish', icon: '🏦', requirement: 2500, stat: 'totalFishSold' },
  { id: 'sold_3k', name: 'Export Manager', title: 'Export Manager', desc: 'Sell 3,000 fish', icon: '🚢', requirement: 3000, stat: 'totalFishSold' },
  { id: 'sold_4k', name: 'Trade Route', title: 'Trade Route', desc: 'Sell 4,000 fish', icon: '🗺️', requirement: 4000, stat: 'totalFishSold' },
  { id: 'sold_5k', name: 'Global Exporter', title: 'Global Exporter', desc: 'Sell 5,000 fish', icon: '🌐', requirement: 5000, stat: 'totalFishSold' },
  { id: 'sold_7_5k', name: 'Shipping Magnate', title: 'Shipping Magnate', desc: 'Sell 7,500 fish', icon: '⛴️', requirement: 7500, stat: 'totalFishSold' },
  { id: 'sold_10k', name: 'Logistics King', title: 'Logistics King', desc: 'Sell 10,000 fish', icon: '🏗️', requirement: 10000, stat: 'totalFishSold' },
  { id: 'sold_15k', name: 'Supply Baron', title: 'Supply Baron', desc: 'Sell 15,000 fish', icon: '🎩', requirement: 15000, stat: 'totalFishSold' },
  { id: 'sold_20k', name: 'Trade Emperor', title: 'Trade Emperor', desc: 'Sell 20,000 fish', icon: '👑', requirement: 20000, stat: 'totalFishSold' },
  { id: 'sold_25k', name: 'Market Monopolist', title: 'Market Monopolist', desc: 'Sell 25,000 fish', icon: '🧐', requirement: 25000, stat: 'totalFishSold' },
  { id: 'sold_30k', name: 'Fish Monger King', title: 'Fish Monger King', desc: 'Sell 30,000 fish', icon: '🤴', requirement: 30000, stat: 'totalFishSold' },
  { id: 'sold_40k', name: 'Ocean Vendor', title: 'Ocean Vendor', desc: 'Sell 40,000 fish', icon: '🌊', requirement: 40000, stat: 'totalFishSold' },
  { id: 'sold_50k', name: 'Trade God', title: 'Trade God', desc: 'Sell 50,000 fish', icon: '⚖️', requirement: 50000, stat: 'totalFishSold' },
  { id: 'sold_75k', name: 'Economy Pillar', title: 'Economy Pillar', desc: 'Sell 75,000 fish', icon: '🏛️', requirement: 75000, stat: 'totalFishSold' },
  { id: 'sold_100k', name: 'Sales Legend', title: 'Sales Legend', desc: 'Sell 100,000 fish', icon: '🧧', requirement: 100000, stat: 'totalFishSold' },
  { id: 'sold_150k', name: 'Sales Myth', title: 'Sales Myth', desc: 'Sell 150,000 fish', icon: '🧞', requirement: 150000, stat: 'totalFishSold' },
  { id: 'sold_200k', name: 'Sales Titan', title: 'Sales Titan', desc: 'Sell 200,000 fish', icon: '🦾', requirement: 200000, stat: 'totalFishSold' },
  { id: 'sold_250k', name: 'Sales Colossus', title: 'Sales Colossus', desc: 'Sell 250,000 fish', icon: '🗿', requirement: 250000, stat: 'totalFishSold' },
  { id: 'sold_500k', name: 'Sales Behemoth', title: 'Sales Behemoth', desc: 'Sell 500,000 fish', icon: '🐘', requirement: 500000, stat: 'totalFishSold' },
  { id: 'sold_750k', name: 'Sales Leviathan', title: 'Sales Leviathan', desc: 'Sell 750,000 fish', icon: '🐋', requirement: 750000, stat: 'totalFishSold' },
  { id: 'sold_1m', name: 'Million Seller', title: 'Million Seller', desc: 'Sell 1,000,000 fish', icon: '1️⃣', requirement: 1000000, stat: 'totalFishSold' },
  { id: 'sold_2_5m', name: 'Multi-Million Seller', title: 'Multi-Million Seller', desc: 'Sell 2,500,000 fish', icon: '🔢', requirement: 2500000, stat: 'totalFishSold' },
  { id: 'sold_5m', name: 'Mega Seller', title: 'Mega Seller', desc: 'Sell 5,000,000 fish', icon: 'Ⓜ️', requirement: 5000000, stat: 'totalFishSold' },
  { id: 'sold_10m', name: 'Giga Seller', title: 'Giga Seller', desc: 'Sell 10,000,000 fish', icon: '💿', requirement: 10000000, stat: 'totalFishSold' },
  { id: 'sold_50m', name: 'Tera Seller', title: 'Tera Seller', desc: 'Sell 50,000,000 fish', icon: '💾', requirement: 50000000, stat: 'totalFishSold' },
  { id: 'sold_100m', name: 'Universal Seller', title: 'Universal Seller', desc: 'Sell 100,000,000 fish', icon: '🌌', requirement: 100000000, stat: 'totalFishSold' },
  { id: 'sold_500m', name: 'Infinite Seller', title: 'Infinite Seller', desc: 'Sell 500,000,000 fish', icon: '♾️', requirement: 500000000, stat: 'totalFishSold' },
  { id: 'sold_1b', name: 'The Market Itself', title: 'The Market Itself', desc: 'Sell 1,000,000,000 fish', icon: '⬛', requirement: 1000000000, stat: 'totalFishSold' },

  // ==========================================
  // 7. TOTAL STAT UPGRADES (30 Achievements)
  // ==========================================
  { id: 'upg_5', name: 'Power Up', title: 'Power Up', desc: 'Upgrade stats 5 times', icon: '⚡', requirement: 5, stat: 'statsUpgraded' },
  { id: 'upg_10', name: 'Training', title: 'Training', desc: 'Upgrade stats 10 times', icon: '👟', requirement: 10, stat: 'statsUpgraded' },
  { id: 'upg_25', name: 'Dedicated', title: 'Dedicated', desc: 'Upgrade stats 25 times', icon: '🩹', requirement: 25, stat: 'statsUpgraded' },
  { id: 'upg_50', name: 'Heavy Lifter', title: 'Heavy Lifter', desc: 'Upgrade stats 50 times', icon: '🏋️', requirement: 50, stat: 'statsUpgraded' },
  { id: 'upg_75', name: 'Getting Stronger', title: 'Getting Stronger', desc: 'Upgrade stats 75 times', icon: '🥗', requirement: 75, stat: 'statsUpgraded' },
  { id: 'upg_100', name: 'Max Power', title: 'Max Power', desc: 'Upgrade stats 100 times', icon: '🔥', requirement: 100, stat: 'statsUpgraded' },
  { id: 'upg_150', name: 'Gym Rat', title: 'Gym Rat', desc: 'Upgrade stats 150 times', icon: '🐁', requirement: 150, stat: 'statsUpgraded' },
  { id: 'upg_200', name: 'Bodybuilder', title: 'Bodybuilder', desc: 'Upgrade stats 200 times', icon: '💪', requirement: 200, stat: 'statsUpgraded' },
  { id: 'upg_300', name: 'Athlete', title: 'Athlete', desc: 'Upgrade stats 300 times', icon: '⛹️', requirement: 300, stat: 'statsUpgraded' },
  { id: 'upg_400', name: 'Olympian', title: 'Olympian', desc: 'Upgrade stats 400 times', icon: '🏊', requirement: 400, stat: 'statsUpgraded' },
  { id: 'upg_500', name: 'Limit Breaker', title: 'Limit Breaker', desc: 'Upgrade stats 500 times', icon: '🧨', requirement: 500, stat: 'statsUpgraded' },
  { id: 'upg_750', name: 'Superhuman', title: 'Superhuman', desc: 'Upgrade stats 750 times', icon: '🦸', requirement: 750, stat: 'statsUpgraded' },
  { id: 'upg_1k', name: 'Ascension', title: 'Ascension', desc: 'Upgrade stats 1,000 times', icon: '🕊️', requirement: 1000, stat: 'statsUpgraded' },
  { id: 'upg_1_5k', name: 'Evolution', title: 'Evolution', desc: 'Upgrade stats 1,500 times', icon: '🧬', requirement: 1500, stat: 'statsUpgraded' },
  { id: 'upg_2k', name: 'Apex Predator', title: 'Apex Predator', desc: 'Upgrade stats 2,000 times', icon: '🦈', requirement: 2000, stat: 'statsUpgraded' },
  { id: 'upg_3k', name: 'Monster', title: 'Monster', desc: 'Upgrade stats 3,000 times', icon: '👺', requirement: 3000, stat: 'statsUpgraded' },
  { id: 'upg_4k', name: 'Kaiju', title: 'Kaiju', desc: 'Upgrade stats 4,000 times', icon: '🦖', requirement: 4000, stat: 'statsUpgraded' },
  { id: 'upg_5k', name: 'Godly Form', title: 'Godly Form', desc: 'Upgrade stats 5,000 times', icon: '🪐', requirement: 5000, stat: 'statsUpgraded' },
  { id: 'upg_7_5k', name: 'Demi-God', title: 'Demi-God', desc: 'Upgrade stats 7,500 times', icon: '🌗', requirement: 7500, stat: 'statsUpgraded' },
  { id: 'upg_10k', name: 'Full God', title: 'Full God', desc: 'Upgrade stats 10,000 times', icon: '🌕', requirement: 10000, stat: 'statsUpgraded' },
  { id: 'upg_15k', name: 'Titan Form', title: 'Titan Form', desc: 'Upgrade stats 15,000 times', icon: '🛡️', requirement: 15000, stat: 'statsUpgraded' },
  { id: 'upg_20k', name: 'Colossal', title: 'Colossal', desc: 'Upgrade stats 20,000 times', icon: '🏯', requirement: 20000, stat: 'statsUpgraded' },
  { id: 'upg_25k', name: 'Planetary', title: 'Planetary', desc: 'Upgrade stats 25,000 times', icon: '🌍', requirement: 25000, stat: 'statsUpgraded' },
  { id: 'upg_30k', name: 'Stellar', title: 'Stellar', desc: 'Upgrade stats 30,000 times', icon: '⭐', requirement: 30000, stat: 'statsUpgraded' },
  { id: 'upg_40k', name: 'Galactic', title: 'Galactic', desc: 'Upgrade stats 40,000 times', icon: '🌌', requirement: 40000, stat: 'statsUpgraded' },
  { id: 'upg_50k', name: 'Universal', title: 'Universal', desc: 'Upgrade stats 50,000 times', icon: '👾', requirement: 50000, stat: 'statsUpgraded' },
  { id: 'upg_75k', name: 'Multiversal', title: 'Multiversal', desc: 'Upgrade stats 75,000 times', icon: '🔭', requirement: 75000, stat: 'statsUpgraded' },
  { id: 'upg_100k', name: 'Omnipotent', title: 'Omnipotent', desc: 'Upgrade stats 100,000 times', icon: '👁️', requirement: 100000, stat: 'statsUpgraded' },
  { id: 'upg_250k', name: 'One Above All', title: 'One Above All', desc: 'Upgrade stats 250,000 times', icon: '👑', requirement: 250000, stat: 'statsUpgraded' },
  { id: 'upg_500k', name: 'Developer Mode', title: 'Developer Mode', desc: 'Upgrade stats 500,000 times', icon: '💻', requirement: 500000, stat: 'statsUpgraded' },

  // ==========================================
  // 8. EXOTIC FISH (10 Achievements)
  // ==========================================
  { id: 'exotic_1', name: 'Exotic Discovery', title: 'Exotic Discovery', desc: 'Catch 1 Exotic fish', icon: '🦋', requirement: 1, stat: 'exoticsCaught' },
  { id: 'exotic_3', name: 'Exotic Fan', title: 'Exotic Fan', desc: 'Catch 3 Exotic fish', icon: '🌺', requirement: 3, stat: 'exoticsCaught' },
  { id: 'exotic_5', name: 'Exotic Collector', title: 'Exotic Collector', desc: 'Catch 5 Exotic fish', icon: '🌈', requirement: 5, stat: 'exoticsCaught' },
  { id: 'exotic_10', name: 'Exotic Enthusiast', title: 'Exotic Enthusiast', desc: 'Catch 10 Exotic fish', icon: '🦜', requirement: 10, stat: 'exoticsCaught' },
  { id: 'exotic_25', name: 'Exotic Master', title: 'Exotic Master', desc: 'Catch 25 Exotic fish', icon: '🔮', requirement: 25, stat: 'exoticsCaught' },
  { id: 'exotic_50', name: 'Museum Curator', title: 'Museum Curator', desc: 'Catch 50 Exotic fish', icon: '🏛️', requirement: 50, stat: 'exoticsCaught' },
  { id: 'exotic_100', name: 'Rare Species Expert', title: 'Rare Species Expert', desc: 'Catch 100 Exotic fish', icon: '🧬', requirement: 100, stat: 'exoticsCaught' },
  { id: 'exotic_250', name: 'Exotic Legend', title: 'Exotic Legend', desc: 'Catch 250 Exotic fish', icon: '🧪', requirement: 250, stat: 'exoticsCaught' },
  { id: 'exotic_500', name: 'Alien Hunter', title: 'Alien Hunter', desc: 'Catch 500 Exotic fish', icon: '👽', requirement: 500, stat: 'exoticsCaught' },
  { id: 'exotic_1k', name: 'Xenobiologist', title: 'Xenobiologist', desc: 'Catch 1,000 Exotic fish', icon: '🛸', requirement: 1000, stat: 'exoticsCaught' },

  // ==========================================
  // 9. ARCANE FISH (10 Achievements)
  // ==========================================
  { id: 'arcane_1', name: 'Arcane Awakening', title: 'Arcane Awakening', desc: 'Catch 1 Arcane fish', icon: '✨', requirement: 1, stat: 'arcanesCaught' },
  { id: 'arcane_3', name: 'Arcane Seeker', title: 'Arcane Seeker', desc: 'Catch 3 Arcane fish', icon: '🕯️', requirement: 3, stat: 'arcanesCaught' },
  { id: 'arcane_5', name: 'Magic User', title: 'Magic User', desc: 'Catch 5 Arcane fish', icon: '🧙', requirement: 5, stat: 'arcanesCaught' },
  { id: 'arcane_10', name: 'Arcane Legend', title: 'Arcane Legend', desc: 'Catch 10 Arcane fish', icon: '⚡', requirement: 10, stat: 'arcanesCaught' },
  { id: 'arcane_25', name: 'Mana Master', title: 'Mana Master', desc: 'Catch 25 Arcane fish', icon: '🔮', requirement: 25, stat: 'arcanesCaught' },
  { id: 'arcane_50', name: 'Void Walker', title: 'Void Walker', desc: 'Catch 50 Arcane fish', icon: '🌑', requirement: 50, stat: 'arcanesCaught' },
  { id: 'arcane_100', name: 'Rune Keeper', title: 'Rune Keeper', desc: 'Catch 100 Arcane fish', icon: '🧿', requirement: 100, stat: 'arcanesCaught' },
  { id: 'arcane_250', name: 'Spellbinder', title: 'Spellbinder', desc: 'Catch 250 Arcane fish', icon: '📜', requirement: 250, stat: 'arcanesCaught' },
  { id: 'arcane_500', name: 'Archmage', title: 'Archmage', desc: 'Catch 500 Arcane fish', icon: '🏰', requirement: 500, stat: 'arcanesCaught' },
  { id: 'arcane_1k', name: 'Eldritch Lord', title: 'Eldritch Lord', desc: 'Catch 1,000 Arcane fish', icon: '🦑', requirement: 1000, stat: 'arcanesCaught' },

  // ==========================================
  // 10. TREASURE CHESTS (30 Achievements)
  // ==========================================
  { id: 'chest_1', name: 'Treasure Hunter', title: 'Treasure Hunter', desc: 'Find 1 treasure chest', icon: '📦', requirement: 1, stat: 'treasureChestsFound' },
  { id: 'chest_5', name: 'Lucky Find', title: 'Lucky Find', desc: 'Find 5 treasure chests', icon: '🗝️', requirement: 5, stat: 'treasureChestsFound' },
  { id: 'chest_10', name: 'Scavenger', title: 'Scavenger', desc: 'Find 10 treasure chests', icon: '🔦', requirement: 10, stat: 'treasureChestsFound' },
  { id: 'chest_25', name: 'Chest Seeker', title: 'Chest Seeker', desc: 'Find 25 treasure chests', icon: '💎', requirement: 25, stat: 'treasureChestsFound' },
  { id: 'chest_50', name: 'Loot Goblin', title: 'Loot Goblin', desc: 'Find 50 treasure chests', icon: '👺', requirement: 50, stat: 'treasureChestsFound' },
  { id: 'chest_75', name: 'Excavator', title: 'Excavator', desc: 'Find 75 treasure chests', icon: '⛏️', requirement: 75, stat: 'treasureChestsFound' },
  { id: 'chest_100', name: 'Fortune Finder', title: 'Fortune Finder', desc: 'Find 100 treasure chests', icon: '🏴‍☠️', requirement: 100, stat: 'treasureChestsFound' },
  { id: 'chest_150', name: 'Gold Digger', title: 'Gold Digger', desc: 'Find 150 treasure chests', icon: '⛏️', requirement: 150, stat: 'treasureChestsFound' },
  { id: 'chest_200', name: 'Prospector', title: 'Prospector', desc: 'Find 200 treasure chests', icon: '🤠', requirement: 200, stat: 'treasureChestsFound' },
  { id: 'chest_250', name: 'Deep Diver', title: 'Deep Diver', desc: 'Find 250 treasure chests', icon: '🤿', requirement: 250, stat: 'treasureChestsFound' },
  { id: 'chest_350', name: 'Salvage Expert', title: 'Salvage Expert', desc: 'Find 350 treasure chests', icon: '🏗️', requirement: 350, stat: 'treasureChestsFound' },
  { id: 'chest_500', name: 'Sunken Riches', title: 'Sunken Riches', desc: 'Find 500 treasure chests', icon: '👑', requirement: 500, stat: 'treasureChestsFound' },
  { id: 'chest_750', name: 'Tomb Raider', title: 'Tomb Raider', desc: 'Find 750 treasure chests', icon: '🧗', requirement: 750, stat: 'treasureChestsFound' },
  { id: 'chest_1k', name: 'Vault Breaker', title: 'Vault Breaker', desc: 'Find 1,000 treasure chests', icon: '🔐', requirement: 1000, stat: 'treasureChestsFound' },
  { id: 'chest_1_5k', name: 'Dungeon Master', title: 'Dungeon Master', desc: 'Find 1,500 treasure chests', icon: '🏰', requirement: 1500, stat: 'treasureChestsFound' },
  { id: 'chest_2k', name: 'Loot Lord', title: 'Loot Lord', desc: 'Find 2,000 treasure chests', icon: '🤴', requirement: 2000, stat: 'treasureChestsFound' },
  { id: 'chest_3k', name: 'Hoard Hunter', title: 'Hoard Hunter', desc: 'Find 3,000 treasure chests', icon: '🐉', requirement: 3000, stat: 'treasureChestsFound' },
  { id: 'chest_4k', name: 'Chest Maniac', title: 'Chest Maniac', desc: 'Find 4,000 treasure chests', icon: '🤪', requirement: 4000, stat: 'treasureChestsFound' },
  { id: 'chest_5k', name: 'Treasure King', title: 'Treasure King', desc: 'Find 5,000 treasure chests', icon: '👑', requirement: 5000, stat: 'treasureChestsFound' },
  { id: 'chest_7_5k', name: 'Loot God', title: 'Loot God', desc: 'Find 7,500 treasure chests', icon: '🛐', requirement: 7500, stat: 'treasureChestsFound' },
  { id: 'chest_10k', name: 'Greed Incarnate', title: 'Greed Incarnate', desc: 'Find 10,000 treasure chests', icon: '😈', requirement: 10000, stat: 'treasureChestsFound' },
  { id: 'chest_15k', name: 'Endless Loot', title: 'Endless Loot', desc: 'Find 15,000 treasure chests', icon: '🔁', requirement: 15000, stat: 'treasureChestsFound' },
  { id: 'chest_20k', name: 'Mimic Hunter', title: 'Mimic Hunter', desc: 'Find 20,000 treasure chests', icon: '🦷', requirement: 20000, stat: 'treasureChestsFound' },
  { id: 'chest_25k', name: 'Chest Connoisseur', title: 'Chest Connoisseur', desc: 'Find 25,000 treasure chests', icon: '🧐', requirement: 25000, stat: 'treasureChestsFound' },
  { id: 'chest_50k', name: 'Box Opener', title: 'Box Opener', desc: 'Find 50,000 treasure chests', icon: '📦', requirement: 50000, stat: 'treasureChestsFound' },
  { id: 'chest_75k', name: 'Key Master', title: 'Key Master', desc: 'Find 75,000 treasure chests', icon: '🔑', requirement: 75000, stat: 'treasureChestsFound' },
  { id: 'chest_100k', name: 'Pandora', title: 'Pandora', desc: 'Find 100,000 treasure chests', icon: '🏺', requirement: 100000, stat: 'treasureChestsFound' },
  { id: 'chest_250k', name: 'Loot Galaxy', title: 'Loot Galaxy', desc: 'Find 250,000 treasure chests', icon: '🌌', requirement: 250000, stat: 'treasureChestsFound' },
  { id: 'chest_500k', name: 'Loot Universe', title: 'Loot Universe', desc: 'Find 500,000 treasure chests', icon: '🪐', requirement: 500000, stat: 'treasureChestsFound' },
  { id: 'chest_1m', name: 'The One Piece', title: 'The One Piece', desc: 'Find 1,000,000 treasure chests', icon: '👒', requirement: 1000000, stat: 'treasureChestsFound' },

  // ==========================================
  // 11. STRENGTH UPGRADES (30 Achievements)
  // ==========================================
  { id: 'str_1', name: 'First Rep', title: 'First Rep', desc: 'Upgrade Strength 1 time', icon: '☝️', requirement: 1, stat: 'strUpgraded' },
  { id: 'str_5', name: 'Warmup', title: 'Warmup', desc: 'Upgrade Strength 5 times', icon: '🥵', requirement: 5, stat: 'strUpgraded' },
  { id: 'str_10', name: 'Gym Rat', title: 'Gym Rat', desc: 'Upgrade Strength 10 times', icon: '💪', requirement: 10, stat: 'strUpgraded' },
  { id: 'str_25', name: 'Gains', title: 'Gains', desc: 'Upgrade Strength 25 times', icon: '🦾', requirement: 25, stat: 'strUpgraded' },
  { id: 'str_50', name: 'Powerhouse', title: 'Powerhouse', desc: 'Upgrade Strength 50 times', icon: '🏋️', requirement: 50, stat: 'strUpgraded' },
  { id: 'str_75', name: 'Bulking', title: 'Bulking', desc: 'Upgrade Strength 75 times', icon: '🦍', requirement: 75, stat: 'strUpgraded' },
  { id: 'str_100', name: 'Strongman', title: 'Strongman', desc: 'Upgrade Strength 100 times', icon: '🚜', requirement: 100, stat: 'strUpgraded' },
  { id: 'str_150', name: 'Heavy Hitter', title: 'Heavy Hitter', desc: 'Upgrade Strength 150 times', icon: '🔨', requirement: 150, stat: 'strUpgraded' },
  { id: 'str_200', name: 'Titan Strength', title: 'Titan Strength', desc: 'Upgrade Strength 200 times', icon: '⚔️', requirement: 200, stat: 'strUpgraded' },
  { id: 'str_300', name: 'Herculean', title: 'Herculean', desc: 'Upgrade Strength 300 times', icon: '🏛️', requirement: 300, stat: 'strUpgraded' },
  { id: 'str_400', name: 'Beast Mode', title: 'Beast Mode', desc: 'Upgrade Strength 400 times', icon: '🐗', requirement: 400, stat: 'strUpgraded' },
  { id: 'str_500', name: 'Atlas', title: 'Atlas', desc: 'Upgrade Strength 500 times', icon: '🌍', requirement: 500, stat: 'strUpgraded' },
  { id: 'str_750', name: 'Mountain Mover', title: 'Mountain Mover', desc: 'Upgrade Strength 750 times', icon: '🏔️', requirement: 750, stat: 'strUpgraded' },
  { id: 'str_1k', name: 'Earth Shaker', title: 'Earth Shaker', desc: 'Upgrade Strength 1,000 times', icon: '🌋', requirement: 1000, stat: 'strUpgraded' },
  { id: 'str_1_5k', name: 'Planet Cracker', title: 'Planet Cracker', desc: 'Upgrade Strength 1,500 times', icon: '☄️', requirement: 1500, stat: 'strUpgraded' },
  { id: 'str_2k', name: 'Star Lifter', title: 'Star Lifter', desc: 'Upgrade Strength 2,000 times', icon: '☀️', requirement: 2000, stat: 'strUpgraded' },
  { id: 'str_3k', name: 'Galaxy Thrower', title: 'Galaxy Thrower', desc: 'Upgrade Strength 3,000 times', icon: '🌌', requirement: 3000, stat: 'strUpgraded' },
  { id: 'str_4k', name: 'Physics Breaker', title: 'Physics Breaker', desc: 'Upgrade Strength 4,000 times', icon: '⚛️', requirement: 4000, stat: 'strUpgraded' },
  { id: 'str_5k', name: 'Infinite Power', title: 'Infinite Power', desc: 'Upgrade Strength 5,000 times', icon: '♾️', requirement: 5000, stat: 'strUpgraded' },
  { id: 'str_7_5k', name: 'God of War', title: 'God of War', desc: 'Upgrade Strength 7,500 times', icon: '🛡️', requirement: 7500, stat: 'strUpgraded' },
  { id: 'str_10k', name: 'Strength Incarnate', title: 'Strength Incarnate', desc: 'Upgrade Strength 10,000 times', icon: '🛐', requirement: 10000, stat: 'strUpgraded' },
  { id: 'str_15k', name: 'Absolute Force', title: 'Absolute Force', desc: 'Upgrade Strength 15,000 times', icon: '💥', requirement: 15000, stat: 'strUpgraded' },
  { id: 'str_20k', name: 'Unstoppable Object', title: 'Unstoppable Object', desc: 'Upgrade Strength 20,000 times', icon: '🛑', requirement: 20000, stat: 'strUpgraded' },
  { id: 'str_25k', name: 'Immovable', title: 'Immovable', desc: 'Upgrade Strength 25,000 times', icon: '🧱', requirement: 25000, stat: 'strUpgraded' },
  { id: 'str_50k', name: 'The Strongest', title: 'The Strongest', desc: 'Upgrade Strength 50,000 times', icon: '🥇', requirement: 50000, stat: 'strUpgraded' },
  { id: 'str_75k', name: 'One Punch', title: 'One Punch', desc: 'Upgrade Strength 75,000 times', icon: '🥊', requirement: 75000, stat: 'strUpgraded' },
  { id: 'str_100k', name: 'Limitless', title: 'Limitless', desc: 'Upgrade Strength 100,000 times', icon: '🆙', requirement: 100000, stat: 'strUpgraded' },
  { id: 'str_250k', name: 'Strength Singularity', title: 'Strength Singularity', desc: 'Upgrade Strength 250,000 times', icon: '🕳️', requirement: 250000, stat: 'strUpgraded' },
  { id: 'str_500k', name: 'Universe Carrier', title: 'Universe Carrier', desc: 'Upgrade Strength 500,000 times', icon: '🏋️‍♂️', requirement: 500000, stat: 'strUpgraded' },
  { id: 'str_1m', name: 'Strength Itself', title: 'Strength Itself', desc: 'Upgrade Strength 1,000,000 times', icon: '🦾', requirement: 1000000, stat: 'strUpgraded' },

  // ==========================================
  // 12. INTELLIGENCE UPGRADES (30 Achievements)
  // ==========================================
  { id: 'int_1', name: 'First Thought', title: 'First Thought', desc: 'Upgrade Intelligence 1 time', icon: '💡', requirement: 1, stat: 'intUpgraded' },
  { id: 'int_5', name: 'Studying', title: 'Studying', desc: 'Upgrade Intelligence 5 times', icon: '📝', requirement: 5, stat: 'intUpgraded' },
  { id: 'int_10', name: 'Quick Learner', title: 'Quick Learner', desc: 'Upgrade Intelligence 10 times', icon: '📚', requirement: 10, stat: 'intUpgraded' },
  { id: 'int_25', name: 'Bookworm', title: 'Bookworm', desc: 'Upgrade Intelligence 25 times', icon: '👓', requirement: 25, stat: 'intUpgraded' },
  { id: 'int_50', name: 'Genius Trader', title: 'Genius Trader', desc: 'Upgrade Intelligence 50 times', icon: '🧠', requirement: 50, stat: 'intUpgraded' },
  { id: 'int_75', name: 'Honors Student', title: 'Honors Student', desc: 'Upgrade Intelligence 75 times', icon: '🎓', requirement: 75, stat: 'intUpgraded' },
  { id: 'int_100', name: 'Scholar', title: 'Scholar', desc: 'Upgrade Intelligence 100 times', icon: '📜', requirement: 100, stat: 'intUpgraded' },
  { id: 'int_150', name: 'Professor', title: 'Professor', desc: 'Upgrade Intelligence 150 times', icon: '👨‍🏫', requirement: 150, stat: 'intUpgraded' },
  { id: 'int_200', name: 'Market Sage', title: 'Market Sage', desc: 'Upgrade Intelligence 200 times', icon: '🧙‍♂️', requirement: 200, stat: 'intUpgraded' },
  { id: 'int_300', name: 'Oracle', title: 'Oracle', desc: 'Upgrade Intelligence 300 times', icon: '🔮', requirement: 300, stat: 'intUpgraded' },
  { id: 'int_400', name: 'Visionary', title: 'Visionary', desc: 'Upgrade Intelligence 400 times', icon: '👁️', requirement: 400, stat: 'intUpgraded' },
  { id: 'int_500', name: 'Omniscient', title: 'Omniscient', desc: 'Upgrade Intelligence 500 times', icon: '🌐', requirement: 500, stat: 'intUpgraded' },
  { id: 'int_750', name: 'Mastermind', title: 'Mastermind', desc: 'Upgrade Intelligence 750 times', icon: '♟️', requirement: 750, stat: 'intUpgraded' },
  { id: 'int_1k', name: 'Big Brain', title: 'Big Brain', desc: 'Upgrade Intelligence 1,000 times', icon: '🤯', requirement: 1000, stat: 'intUpgraded' },
  { id: 'int_1_5k', name: 'Telepath', title: 'Telepath', desc: 'Upgrade Intelligence 1,500 times', icon: '📡', requirement: 1500, stat: 'intUpgraded' },
  { id: 'int_2k', name: 'Futurist', title: 'Futurist', desc: 'Upgrade Intelligence 2,000 times', icon: '🤖', requirement: 2000, stat: 'intUpgraded' },
  { id: 'int_3k', name: 'Super Computer', title: 'Super Computer', desc: 'Upgrade Intelligence 3,000 times', icon: '🖥️', requirement: 3000, stat: 'intUpgraded' },
  { id: 'int_4k', name: 'AI Overlord', title: 'AI Overlord', desc: 'Upgrade Intelligence 4,000 times', icon: '💾', requirement: 4000, stat: 'intUpgraded' },
  { id: 'int_5k', name: 'Neural Network', title: 'Neural Network', desc: 'Upgrade Intelligence 5,000 times', icon: '🕸️', requirement: 5000, stat: 'intUpgraded' },
  { id: 'int_7_5k', name: 'Hive Mind', title: 'Hive Mind', desc: 'Upgrade Intelligence 7,500 times', icon: '🐝', requirement: 7500, stat: 'intUpgraded' },
  { id: 'int_10k', name: 'Knowledge God', title: 'Knowledge God', desc: 'Upgrade Intelligence 10,000 times', icon: '🛐', requirement: 10000, stat: 'intUpgraded' },
  { id: 'int_15k', name: 'Akashic Reader', title: 'Akashic Reader', desc: 'Upgrade Intelligence 15,000 times', icon: '📖', requirement: 15000, stat: 'intUpgraded' },
  { id: 'int_20k', name: 'All Seeing', title: 'All Seeing', desc: 'Upgrade Intelligence 20,000 times', icon: '🧿', requirement: 20000, stat: 'intUpgraded' },
  { id: 'int_25k', name: 'Prophet', title: 'Prophet', desc: 'Upgrade Intelligence 25,000 times', icon: '☪️', requirement: 25000, stat: 'intUpgraded' },
  { id: 'int_50k', name: 'The Wisest', title: 'The Wisest', desc: 'Upgrade Intelligence 50,000 times', icon: '🦉', requirement: 50000, stat: 'intUpgraded' },
  { id: 'int_75k', name: 'Cosmic Mind', title: 'Cosmic Mind', desc: 'Upgrade Intelligence 75,000 times', icon: '🌌', requirement: 75000, stat: 'intUpgraded' },
  { id: 'int_100k', name: 'Living Library', title: 'Living Library', desc: 'Upgrade Intelligence 100,000 times', icon: '🏯', requirement: 100000, stat: 'intUpgraded' },
  { id: 'int_250k', name: 'Mind Over Matter', title: 'Mind Over Matter', desc: 'Upgrade Intelligence 250,000 times', icon: '🧘', requirement: 250000, stat: 'intUpgraded' },
  { id: 'int_500k', name: 'Universal Brain', title: 'Universal Brain', desc: 'Upgrade Intelligence 500,000 times', icon: '🧠', requirement: 500000, stat: 'intUpgraded' },
  { id: 'int_1m', name: 'Intelligence Itself', title: 'Intelligence Itself', desc: 'Upgrade Intelligence 1,000,000 times', icon: '💡', requirement: 1000000, stat: 'intUpgraded' },

  // ==========================================
  // 13. LUCK UPGRADES (30 Achievements)
  // ==========================================
  { id: 'luck_1', name: 'Fingers Crossed', title: 'Fingers Crossed', desc: 'Upgrade Luck 1 time', icon: '🤞', requirement: 1, stat: 'luckUpgraded' },
  { id: 'luck_5', name: 'Beginner\'s Luck', desc: 'Upgrade Luck 5 times', icon: '☘️', requirement: 5, stat: 'luckUpgraded' },
  { id: 'luck_10', name: 'Lucky Start', title: 'Lucky Start', desc: 'Upgrade Luck 10 times', icon: '🍀', requirement: 10, stat: 'luckUpgraded' },
  { id: 'luck_25', name: 'Coin Flipper', title: 'Coin Flipper', desc: 'Upgrade Luck 25 times', icon: '🪙', requirement: 25, stat: 'luckUpgraded' },
  { id: 'luck_50', name: 'Fortune Favored', title: 'Fortune Favored', desc: 'Upgrade Luck 50 times', icon: '🎰', requirement: 50, stat: 'luckUpgraded' },
  { id: 'luck_75', name: 'Rabbit Foot', title: 'Rabbit Foot', desc: 'Upgrade Luck 75 times', icon: '🐇', requirement: 75, stat: 'luckUpgraded' },
  { id: 'luck_100', name: 'High Roller', title: 'High Roller', desc: 'Upgrade Luck 100 times', icon: '🎲', requirement: 100, stat: 'luckUpgraded' },
  { id: 'luck_150', name: 'Hot Streak', title: 'Hot Streak', desc: 'Upgrade Luck 150 times', icon: '🔥', requirement: 150, stat: 'luckUpgraded' },
  { id: 'luck_200', name: 'Blessed by RNG', title: 'Blessed by RNG', desc: 'Upgrade Luck 200 times', icon: '🌠', requirement: 200, stat: 'luckUpgraded' },
  { id: 'luck_300', name: 'Walking Charm', title: 'Walking Charm', desc: 'Upgrade Luck 300 times', icon: '🧿', requirement: 300, stat: 'luckUpgraded' },
  { id: 'luck_400', name: 'Jackpot', title: 'Jackpot', desc: 'Upgrade Luck 400 times', icon: '💰', requirement: 400, stat: 'luckUpgraded' },
  { id: 'luck_500', name: 'Fate Bender', title: 'Fate Bender', desc: 'Upgrade Luck 500 times', icon: '🧶', requirement: 500, stat: 'luckUpgraded' },
  { id: 'luck_750', name: 'Leprechaun', title: 'Leprechaun', desc: 'Upgrade Luck 750 times', icon: '🎩', requirement: 750, stat: 'luckUpgraded' },
  { id: 'luck_1k', name: 'Miracle Worker', title: 'Miracle Worker', desc: 'Upgrade Luck 1,000 times', icon: '✨', requirement: 1000, stat: 'luckUpgraded' },
  { id: 'luck_1_5k', name: 'Probability Defier', title: 'Probability Defier', desc: 'Upgrade Luck 1,500 times', icon: '📉', requirement: 1500, stat: 'luckUpgraded' },
  { id: 'luck_2k', name: 'Destiny Child', title: 'Destiny Child', desc: 'Upgrade Luck 2,000 times', icon: '👶', requirement: 2000, stat: 'luckUpgraded' },
  { id: 'luck_3k', name: 'Chaos Theory', title: 'Chaos Theory', desc: 'Upgrade Luck 3,000 times', icon: '🌀', requirement: 3000, stat: 'luckUpgraded' },
  { id: 'luck_4k', name: 'Entropy Master', title: 'Entropy Master', desc: 'Upgrade Luck 4,000 times', icon: '🌡️', requirement: 4000, stat: 'luckUpgraded' },
  { id: 'luck_5k', name: 'Fortuna', title: 'Fortuna', desc: 'Upgrade Luck 5,000 times', icon: '🎡', requirement: 5000, stat: 'luckUpgraded' },
  { id: 'luck_7_5k', name: 'Serendipity', title: 'Serendipity', desc: 'Upgrade Luck 7,500 times', icon: '🦄', requirement: 7500, stat: 'luckUpgraded' },
  { id: 'luck_10k', name: 'Luck God', title: 'Luck God', desc: 'Upgrade Luck 10,000 times', icon: '🛐', requirement: 10000, stat: 'luckUpgraded' },
  { id: 'luck_15k', name: 'Kismet', title: 'Kismet', desc: 'Upgrade Luck 15,000 times', icon: '🕌', requirement: 15000, stat: 'luckUpgraded' },
  { id: 'luck_20k', name: 'Karma King', title: 'Karma King', desc: 'Upgrade Luck 20,000 times', icon: '☯️', requirement: 20000, stat: 'luckUpgraded' },
  { id: 'luck_25k', name: 'RNGesus', title: 'RNGesus', desc: 'Upgrade Luck 25,000 times', icon: '⛪', requirement: 25000, stat: 'luckUpgraded' },
  { id: 'luck_50k', name: 'The Luckiest', title: 'The Luckiest', desc: 'Upgrade Luck 50,000 times', icon: '🌈', requirement: 50000, stat: 'luckUpgraded' },
  { id: 'luck_75k', name: 'Reality Warper', title: 'Reality Warper', desc: 'Upgrade Luck 75,000 times', icon: '🖍️', requirement: 75000, stat: 'luckUpgraded' },
  { id: 'luck_100k', name: 'Infinite Luck', title: 'Infinite Luck', desc: 'Upgrade Luck 100,000 times', icon: '♾️', requirement: 100000, stat: 'luckUpgraded' },
  { id: 'luck_250k', name: 'Fate Weaver', title: 'Fate Weaver', desc: 'Upgrade Luck 250,000 times', icon: '🕸️', requirement: 250000, stat: 'luckUpgraded' },
  { id: 'luck_500k', name: 'Destiny Writer', title: 'Destiny Writer', desc: 'Upgrade Luck 500,000 times', icon: '✒️', requirement: 500000, stat: 'luckUpgraded' },
  { id: 'luck_1m', name: 'Luck Itself', title: 'Luck Itself', desc: 'Upgrade Luck 1,000,000 times', icon: '🍀', requirement: 1000000, stat: 'luckUpgraded' },

  // ==========================================
  // 14. STAMINA UPGRADES (30 Achievements)
  // ==========================================
  { id: 'stam_1', name: 'Stretching', title: 'Stretching', desc: 'Upgrade Stamina 1 time', icon: '🙆', requirement: 1, stat: 'staminaUpgraded' },
  { id: 'stam_5', name: 'Jogger', title: 'Jogger', desc: 'Upgrade Stamina 5 times', icon: '🏃', requirement: 5, stat: 'staminaUpgraded' },
  { id: 'stam_10', name: 'Building Endurance', title: 'Building Endurance', desc: 'Upgrade Stamina 10 times', icon: '👟', requirement: 10, stat: 'staminaUpgraded' },
  { id: 'stam_25', name: 'Hiker', title: 'Hiker', desc: 'Upgrade Stamina 25 times', icon: '🥾', requirement: 25, stat: 'staminaUpgraded' },
  { id: 'stam_50', name: 'Marathon Fisher', title: 'Marathon Fisher', desc: 'Upgrade Stamina 50 times', icon: '⏱️', requirement: 50, stat: 'staminaUpgraded' },
  { id: 'stam_75', name: 'Sprinter', title: 'Sprinter', desc: 'Upgrade Stamina 75 times', icon: '💨', requirement: 75, stat: 'staminaUpgraded' },
  { id: 'stam_100', name: 'Ironman', title: 'Ironman', desc: 'Upgrade Stamina 100 times', icon: '🔋', requirement: 100, stat: 'staminaUpgraded' },
  { id: 'stam_150', name: 'Triathlete', title: 'Triathlete', desc: 'Upgrade Stamina 150 times', icon: '🏊', requirement: 150, stat: 'staminaUpgraded' },
  { id: 'stam_200', name: 'Tireless Angler', title: 'Tireless Angler', desc: 'Upgrade Stamina 200 times', icon: '♾️', requirement: 200, stat: 'staminaUpgraded' },
  { id: 'stam_300', name: 'The Machine', title: 'The Machine', desc: 'Upgrade Stamina 300 times', icon: '🤖', requirement: 300, stat: 'staminaUpgraded' },
  { id: 'stam_400', name: 'Energizer', title: 'Energizer', desc: 'Upgrade Stamina 400 times', icon: '🐰', requirement: 400, stat: 'staminaUpgraded' },
  { id: 'stam_500', name: 'Unsleeping', title: 'Unsleeping', desc: 'Upgrade Stamina 500 times', icon: '🧛', requirement: 500, stat: 'staminaUpgraded' },
  { id: 'stam_750', name: 'Perpetual Motion', title: 'Perpetual Motion', desc: 'Upgrade Stamina 750 times', icon: '🔄', requirement: 750, stat: 'staminaUpgraded' },
  { id: 'stam_1k', name: 'Limitless Energy', title: 'Limitless Energy', desc: 'Upgrade Stamina 1,000 times', icon: '⚡', requirement: 1000, stat: 'staminaUpgraded' },
  { id: 'stam_1_5k', name: 'Everlasting', title: 'Everlasting', desc: 'Upgrade Stamina 1,500 times', icon: '🌲', requirement: 1500, stat: 'staminaUpgraded' },
  { id: 'stam_2k', name: 'Undying', title: 'Undying', desc: 'Upgrade Stamina 2,000 times', icon: '🧟', requirement: 2000, stat: 'staminaUpgraded' },
  { id: 'stam_3k', name: 'Immortal Body', title: 'Immortal Body', desc: 'Upgrade Stamina 3,000 times', icon: '🛡️', requirement: 3000, stat: 'staminaUpgraded' },
  { id: 'stam_4k', name: 'Phoenix', title: 'Phoenix', desc: 'Upgrade Stamina 4,000 times', icon: '🐦', requirement: 4000, stat: 'staminaUpgraded' },
  { id: 'stam_5k', name: 'Vitality God', title: 'Vitality God', desc: 'Upgrade Stamina 5,000 times', icon: '❤️', requirement: 5000, stat: 'staminaUpgraded' },
  { id: 'stam_7_5k', name: 'Indestructible', title: 'Indestructible', desc: 'Upgrade Stamina 7,500 times', icon: '🧱', requirement: 7500, stat: 'staminaUpgraded' },
  { id: 'stam_10k', name: 'Stamina God', title: 'Stamina God', desc: 'Upgrade Stamina 10,000 times', icon: '🛐', requirement: 10000, stat: 'staminaUpgraded' },
  { id: 'stam_15k', name: 'Eternal Flame', title: 'Eternal Flame', desc: 'Upgrade Stamina 15,000 times', icon: '🔥', requirement: 15000, stat: 'staminaUpgraded' },
  { id: 'stam_20k', name: 'Nuclear Core', title: 'Nuclear Core', desc: 'Upgrade Stamina 20,000 times', icon: '☢️', requirement: 20000, stat: 'staminaUpgraded' },
  { id: 'stam_25k', name: 'Star Heart', title: 'Star Heart', desc: 'Upgrade Stamina 25,000 times', icon: '⭐', requirement: 25000, stat: 'staminaUpgraded' },
  { id: 'stam_50k', name: 'The Fittest', title: 'The Fittest', desc: 'Upgrade Stamina 50,000 times', icon: '🏋️', requirement: 50000, stat: 'staminaUpgraded' },
  { id: 'stam_75k', name: 'Timeless', title: 'Timeless', desc: 'Upgrade Stamina 75,000 times', icon: '⏳', requirement: 75000, stat: 'staminaUpgraded' },
  { id: 'stam_100k', name: 'Infinite Stamina', title: 'Infinite Stamina', desc: 'Upgrade Stamina 100,000 times', icon: '♾️', requirement: 100000, stat: 'staminaUpgraded' },
  { id: 'stam_250k', name: 'Singularity Heart', title: 'Singularity Heart', desc: 'Upgrade Stamina 250,000 times', icon: '💓', requirement: 250000, stat: 'staminaUpgraded' },
  { id: 'stam_500k', name: 'Galaxy Engine', title: 'Galaxy Engine', desc: 'Upgrade Stamina 500,000 times', icon: '⚙️', requirement: 500000, stat: 'staminaUpgraded' },
  { id: 'stam_1m', name: 'Stamina Itself', title: 'Stamina Itself', desc: 'Upgrade Stamina 1,000,000 times', icon: '🔋', requirement: 1000000, stat: 'staminaUpgraded' },

  // ==========================================
  // 15. RELICS (30 Achievements)
  // ==========================================
  { id: 'relic_1', name: 'Dusty Old Thing', title: 'Dusty Old Thing', desc: 'Earn 1 total relic', icon: '🧹', requirement: 1, stat: 'totalRelicsEarned' },
  { id: 'relic_5', name: 'Curio', title: 'Curio', desc: 'Earn 5 total relics', icon: '🏺', requirement: 5, stat: 'totalRelicsEarned' },
  { id: 'relic_10', name: 'Archaeologist', title: 'Archaeologist', desc: 'Earn 10 total relics', icon: '⛏️', requirement: 10, stat: 'totalRelicsEarned' },
  { id: 'relic_25', name: 'Relic Hunter', title: 'Relic Hunter', desc: 'Earn 25 total relics', icon: '🔦', requirement: 25, stat: 'totalRelicsEarned' },
  { id: 'relic_50', name: 'Relic Collector', title: 'Relic Collector', desc: 'Earn 50 total relics', icon: '💠', requirement: 50, stat: 'totalRelicsEarned' },
  { id: 'relic_100', name: 'Relic Hoarder', title: 'Relic Hoarder', desc: 'Earn 100 total relics', icon: '💍', requirement: 100, stat: 'totalRelicsEarned' },
  { id: 'relic_150', name: 'Antique Dealer', title: 'Antique Dealer', desc: 'Earn 150 total relics', icon: '🧐', requirement: 150, stat: 'totalRelicsEarned' },
  { id: 'relic_200', name: 'Museum Owner', title: 'Museum Owner', desc: 'Earn 200 total relics', icon: '🏛️', requirement: 200, stat: 'totalRelicsEarned' },
  { id: 'relic_300', name: 'Relic Expert', title: 'Relic Expert', desc: 'Earn 300 total relics', icon: '🤓', requirement: 300, stat: 'totalRelicsEarned' },
  { id: 'relic_400', name: 'Historian', title: 'Historian', desc: 'Earn 400 total relics', icon: '📖', requirement: 400, stat: 'totalRelicsEarned' },
  { id: 'relic_500', name: 'Relic Master', title: 'Relic Master', desc: 'Earn 500 total relics', icon: '🎓', requirement: 500, stat: 'totalRelicsEarned' },
  { id: 'relic_750', name: 'Preservationist', title: 'Preservationist', desc: 'Earn 750 total relics', icon: '🛡️', requirement: 750, stat: 'totalRelicsEarned' },
  { id: 'relic_1k', name: 'Relic Tycoon', title: 'Relic Tycoon', desc: 'Earn 1,000 total relics', icon: '💎', requirement: 1000, stat: 'totalRelicsEarned' },
  { id: 'relic_1_5k', name: 'Ancient Keeper', title: 'Ancient Keeper', desc: 'Earn 1,500 total relics', icon: '🗿', requirement: 1500, stat: 'totalRelicsEarned' },
  { id: 'relic_2k', name: 'Time Keeper', title: 'Time Keeper', desc: 'Earn 2,000 total relics', icon: '⏳', requirement: 2000, stat: 'totalRelicsEarned' },
  { id: 'relic_3k', name: 'Past Master', title: 'Past Master', desc: 'Earn 3,000 total relics', icon: '🔙', requirement: 3000, stat: 'totalRelicsEarned' },
  { id: 'relic_4k', name: 'Relic Lord', title: 'Relic Lord', desc: 'Earn 4,000 total relics', icon: '👑', requirement: 4000, stat: 'totalRelicsEarned' },
  { id: 'relic_5k', name: 'Relic God', title: 'Relic God', desc: 'Earn 5,000 total relics', icon: '🛐', requirement: 5000, stat: 'totalRelicsEarned' },
  { id: 'relic_7_5k', name: 'Artifact King', title: 'Artifact King', desc: 'Earn 7,500 total relics', icon: '🗡️', requirement: 7500, stat: 'totalRelicsEarned' },
  { id: 'relic_10k', name: 'History Itself', title: 'History Itself', desc: 'Earn 10,000 total relics', icon: '📜', requirement: 10000, stat: 'totalRelicsEarned' },
  { id: 'relic_15k', name: 'Relic Emperor', title: 'Relic Emperor', desc: 'Earn 15,000 total relics', icon: '🤴', requirement: 15000, stat: 'totalRelicsEarned' },
  { id: 'relic_20k', name: 'Relic Deity', title: 'Relic Deity', desc: 'Earn 20,000 total relics', icon: '🎇', requirement: 20000, stat: 'totalRelicsEarned' },
  { id: 'relic_25k', name: 'Relic Titan', title: 'Relic Titan', desc: 'Earn 25,000 total relics', icon: '👾', requirement: 25000, stat: 'totalRelicsEarned' },
  { id: 'relic_50k', name: 'Relic Behemoth', title: 'Relic Behemoth', desc: 'Earn 50,000 total relics', icon: '🦕', requirement: 50000, stat: 'totalRelicsEarned' },
  { id: 'relic_75k', name: 'Relic Leviathan', title: 'Relic Leviathan', desc: 'Earn 75,000 total relics', icon: '🐉', requirement: 75000, stat: 'totalRelicsEarned' },
  { id: 'relic_100k', name: 'Relic Mountain', title: 'Relic Mountain', desc: 'Earn 100,000 total relics', icon: '🏔️', requirement: 100000, stat: 'totalRelicsEarned' },
  { id: 'relic_250k', name: 'Relic Planet', title: 'Relic Planet', desc: 'Earn 250,000 total relics', icon: '🌍', requirement: 250000, stat: 'totalRelicsEarned' },
  { id: 'relic_500k', name: 'Relic Galaxy', title: 'Relic Galaxy', desc: 'Earn 500,000 total relics', icon: '🌌', requirement: 500000, stat: 'totalRelicsEarned' },
  { id: 'relic_1m', name: 'The First Relic', title: 'The First Relic', desc: 'Earn 1,000,000 total relics', icon: '🏺', requirement: 1000000, stat: 'totalRelicsEarned' },
  { id: 'relic_10m', name: 'Relic Universe', title: 'Relic Universe', desc: 'Earn 10,000,000 total relics', icon: '🪐', requirement: 10000000, stat: 'totalRelicsEarned' },

  // ==========================================
  // 16. GOLD IN POCKET (30 Achievements)
  // ==========================================
  { id: 'pocket_1k', name: 'Piggy Bank', title: 'Piggy Bank', desc: 'Hold 1,000 gold', icon: '🐖', requirement: 1000, stat: 'gold' },
  { id: 'pocket_5k', name: 'Wallet', title: 'Wallet', desc: 'Hold 5,000 gold', icon: '👛', requirement: 5000, stat: 'gold' },
  { id: 'pocket_10k', name: 'Savings Account', title: 'Savings Account', desc: 'Hold 10,000 gold', icon: '💳', requirement: 10000, stat: 'gold' },
  { id: 'pocket_25k', name: 'Briefcase', title: 'Briefcase', desc: 'Hold 25,000 gold', icon: '💼', requirement: 25000, stat: 'gold' },
  { id: 'pocket_50k', name: 'Safe', title: 'Safe', desc: 'Hold 50,000 gold', icon: '🔐', requirement: 50000, stat: 'gold' },
  { id: 'pocket_100k', name: 'Gold Vault', title: 'Gold Vault', desc: 'Hold 100,000 gold', icon: '🏦', requirement: 100000, stat: 'gold' },
  { id: 'pocket_250k', name: 'Investor', title: 'Investor', desc: 'Hold 250,000 gold', icon: '📈', requirement: 250000, stat: 'gold' },
  { id: 'pocket_500k', name: 'Banker', title: 'Banker', desc: 'Hold 500,000 gold', icon: '🏧', requirement: 500000, stat: 'gold' },
  { id: 'pocket_1m', name: 'Dragon Hoard', title: 'Dragon Hoard', desc: 'Hold 1,000,000 gold', icon: '🐉', requirement: 1000000, stat: 'gold' },
  { id: 'pocket_5m', name: 'King\'s Ransom', desc: 'Hold 5,000,000 gold', icon: '👑', requirement: 5000000, stat: 'gold' },
  { id: 'pocket_10m', name: 'Smaug', title: 'Smaug', desc: 'Hold 10,000,000 gold', icon: '🔥', requirement: 10000000, stat: 'gold' },
  { id: 'pocket_50m', name: 'Gold Mountain', title: 'Gold Mountain', desc: 'Hold 50,000,000 gold', icon: '🏔️', requirement: 50000000, stat: 'gold' },
  { id: 'pocket_100m', name: 'Money Bin', title: 'Money Bin', desc: 'Hold 100,000,000 gold', icon: '🏊', requirement: 100000000, stat: 'gold' },
  { id: 'pocket_500m', name: 'Federal Reserve', title: 'Federal Reserve', desc: 'Hold 500,000,000 gold', icon: '🏛️', requirement: 500000000, stat: 'gold' },
  { id: 'pocket_1b', name: 'Scrooge', title: 'Scrooge', desc: 'Hold 1,000,000,000 gold', icon: '🦆', requirement: 1000000000, stat: 'gold' },
  { id: 'pocket_10b', name: 'Golden City', title: 'Golden City', desc: 'Hold 10B gold', icon: '🏙️', requirement: 10000000000, stat: 'gold' },
  { id: 'pocket_100b', name: 'Golden Continent', title: 'Golden Continent', desc: 'Hold 100B gold', icon: '🗺️', requirement: 100000000000, stat: 'gold' },
  { id: 'pocket_1t', name: 'Golden Planet', title: 'Golden Planet', desc: 'Hold 1 Trillion gold', icon: '🪐', requirement: 1000000000000, stat: 'gold' },
  { id: 'pocket_10t', name: 'Golden Star', title: 'Golden Star', desc: 'Hold 10 Trillion gold', icon: '☀️', requirement: 10000000000000, stat: 'gold' },
  { id: 'pocket_100t', name: 'Golden System', title: 'Golden System', desc: 'Hold 100 Trillion gold', icon: '🌌', requirement: 100000000000000, stat: 'gold' },
  { id: 'pocket_1qa', name: 'Golden Galaxy', title: 'Golden Galaxy', desc: 'Hold 1 Quadrillion gold', icon: '🎆', requirement: 1000000000000000, stat: 'gold' },
  { id: 'pocket_10qa', name: 'Golden Cluster', title: 'Golden Cluster', desc: 'Hold 10 Quadrillion gold', icon: '🔭', requirement: 10000000000000000, stat: 'gold' },
  { id: 'pocket_100qa', name: 'Golden Universe', title: 'Golden Universe', desc: 'Hold 100 Quadrillion gold', icon: '♾️', requirement: 100000000000000000, stat: 'gold' },
  { id: 'pocket_1qi', name: 'Golden Multiverse', title: 'Golden Multiverse', desc: 'Hold 1 Quintillion gold', icon: '🔮', requirement: 1000000000000000000, stat: 'gold' },
  { id: 'pocket_10qi', name: 'Reality Buyer', title: 'Reality Buyer', desc: 'Hold 10 Quintillion gold', icon: '🤝', requirement: 10000000000000000000, stat: 'gold' },
  { id: 'pocket_100qi', name: 'Time Buyer', title: 'Time Buyer', desc: 'Hold 100 Quintillion gold', icon: '⌛', requirement: 100000000000000000000, stat: 'gold' },
  { id: 'pocket_1sx', name: 'Concept Buyer', title: 'Concept Buyer', desc: 'Hold 1 Sextillion gold', icon: '🧠', requirement: 1000000000000000000000, stat: 'gold' },
  { id: 'pocket_10sx', name: 'Developer', title: 'Developer', desc: 'Hold 10 Sextillion gold', icon: '💻', requirement: 10000000000000000000000, stat: 'gold' },
  { id: 'pocket_100sx', name: 'Game Owner', title: 'Game Owner', desc: 'Hold 100 Sextillion gold', icon: '📀', requirement: 100000000000000000000000, stat: 'gold' },
  { id: 'pocket_1sp', name: 'Simulation End', title: 'Simulation End', desc: 'Hold 1 Septillion gold', icon: '⛔', requirement: 1000000000000000000000000, stat: 'gold' }
];