// Funny fishing lines
window.FUNNY_LINES = [
"You prayed to the ocean gods and caught:",
      "You accidentally farted underwater and caught:",
      "You threw a gold coin for good luck and caught:",
      "You sang a sea shanty terribly and caught:",
      "You told a bad joke to the fish and caught:",
      "Your bait smelled like pizza and you caught:",
      "You sneezed at the perfect moment and caught:",
      "You whispered sweet nothings to the ocean and caught:",
      "You did a little dance on the boat and caught:",
      "Your fishing rod sneezed (yes, really) and caught:",
      "You blinked three times and magically caught:",
      "A seagull judged your technique but you still caught:",
      "You forgot what you were doing and somehow caught:",
      "You yelled 'YOLO!' into the void and caught:",
      "Your hat flew off and startled you into catching:",
      "You dropped your phone (it's waterproof) and caught:",
      "A dolphin gave you a thumbs up and you caught:",
      "You were daydreaming about lunch and caught:",
      "Pure dumb luck blessed you with:",
      "You used a gummy bear as bait and caught:",
      "You put a picture of your ex on the hook and caught:",
      "You used a soggy french fry and somehow caught:",
      "You forgot to put bait on but still caught:",
      "You used a shiny button you found and caught:",
      "You baited the hook with 'hopes and dreams' and caught:",
      "You used a coupon for 5% off and caught:",
      "You attached a love letter to the hook and caught:",
      "You used a spicy nacho and the fish couldn't resist:",
      "You accidentally dropped your car keys and hooked:",
      "You used a stale marshmallow and caught:",
      "You put a piece of broccoli on the line (weirdo) and caught:",
      "You used a glittery sticker as a lure and caught:",
      "You hooked a fidget spinner to the line and caught:",
      "You used a piece of gum you were chewing and caught:",
      "You sacrificed a perfectly good donut and caught:",
      "You tripped over a bucket and accidentally hooked:",
      "You fell asleep, woke up screaming, and caught:",
      "You cast the line into a tree, it fell, and you caught:",
      "You were looking at a meme on your phone and caught:",
      "You tried to take a selfie and accidentally hooked:",
      "You tangled your line into a knot, pulled, and caught:",
      "You dropped your rod, dove in to get it, and caught:",
      "You cast the line backwards but still caught:",
      "You were busy untangling your beard/hair and caught:",
      "You almost fell overboard but managed to snag:",
      "You sneezed so hard the boat rocked and you caught:",
      "You spilled your coffee into the water and attracted:",
      "You dropped your sunglasses, the fish wore them, and you caught:",
      "A crab pinched your toe, you jerked the rod, and caught:",
      "A dragonfly landed on your nose, you froze, and caught:",
      "The wind whispered 'check this out' and you caught:",
      "A turtle looked at you with pity and you caught:",
      "The water splashed your face, you got mad, and caught:",
      "A duck landed on your head and brought you luck:",
      "The fog cleared for exactly one second and you saw:",
      "A mosquito bit you, you slapped the water, and caught:",
      "The clouds formed a shape that looked like:",
      "The current decided to be nice for once and gave you:",
      "Someone waved at you, you waved back awkwardly, and caught:",
      "You tried to look cool for a passing boat and caught:",
      "Your stomach growled so loud it summoned:",
      "You were explaining how bad you are at fishing and caught:",
      "You bet your friend 5 gold you'd fail, but you caught:",
      "You tried to show off a trick cast, failed, and caught:",
      "You were talking to yourself (we won't judge) and caught:",
      "Your mom called to ask if you ate, and you caught:",
      "You clicked the mouse really hard and caught:",
      "The game developer felt sorry for you and sent:",
      "You experienced a lag spike and suddenly caught:",
      "You mashed the buttons in panic and hooked:",
      "You threatened to uninstall the game and caught:",
      "You turned the graphics settings down and caught:",
      "The RNG gods smiled upon you and gifted:",
      "You were tabbed out watching YouTube and caught:",
      "You almost rage-quit but then you caught:",
      "You rolled a natural 20 on your fishing check and caught:",
      "You used a cheat code (just kidding) and caught:",
      "The server synchronized perfectly for you to catch:",
      "You cast your line into another dimension and pulled out:",
      "Time stopped for a brief moment and you caught:",
      "You fished in a puddle of tears and caught:",
      "Gravity reversed for a second and you caught:",
      "You heard a ghostly 'yeehaw' from the deep and caught:",
      "The fish actually jumped into your boat. It was:",
      "You realized we are all just stardust and caught:",
      "You channeled your inner zen master and caught:",
      "A portal opened, a hand handed you this, and closed:",
      "You asked the water 'what is the meaning of life?' and caught:",
      "The stars aligned in a weird shape and you hooked:",
      "You felt a disturbance in the Force and caught:",
      "Bloop bloop glub glub, you caught:",
      "Your rod started vibrating ominously and you caught:",
      "You closed your eyes and used 'The Force' to catch:",
      "You cast your line into a reflection of the moon and caught:",
      "You decided to fish aggressively and caught:",
      "You decided to fish passively and caught:",
      "You decided to fish sarcastically and caught:",
      "You asked the fish nicely to bite and you caught:",
      "You threatened the water with a spoon and caught:",
      "You successfully performed a rain dance and caught:",
      "Your line got caught on a rock, you yanked it, and found:",
      "Your reel jammed, you kicked it, and somehow caught:",
      "Your hook was rusty but the fish didn't mind:",
      "You used a safety pin instead of a hook and caught:",
      "Your bobber went under 10 minutes ago and you finally caught:",
      "You were busy fixing your inventory and auto-caught:",
      "You were eating a taco and dropped some salsa, catching:",
      "The fish smelled your breath (minty!) and you caught:",
      "You promised the fish a snack and hooked:",
      "You were thinking about steak and accidentally caught:",
      "You caught this at exactly 4:20 PM:",
      "You caught this while thinking about your taxes:",
      "You caught this while scratching your left ear:",
      "You caught this while humming the Tetris theme:",
      "You caught this while worrying about global warming:",
      "Boom! You caught:",
      "Sploosh! You caught:",
      "Yoink! You caught:",
      "Huzzah! You caught:",
      "Success! You caught:",
      "Behold! You caught:",
      "Snap! You caught:",
      "Whoops! You caught:",
      "Finally! You caught:",
      "Guess what? You caught:",
      "The water bubbled suspiciously and you caught:",
      "You felt a tiny tug and pulled up a massive:",
      "You felt a massive tug and pulled up a tiny:",
      "It fought like a demon but it was just:",
      "It didn't fight at all, it just gave up. It was:",
      "You thought you snagged a boot but it was:",
      "You thought you snagged a tire but it was:",
      "You thought you snagged a submarine but it was:",
      "A mermaid winked at you and you caught:",
      "Poseidon owes you money so he sent:",
      "The Loch Ness monster spat this out:",
      "You cast into a whirlpool and pulled out:",
      "You cast into a rainbow reflection and found:",
      "Your line got struck by lightning (mildly) and you caught:",
      "You used a magnet (cheater) and caught:",
      "You simply asked the water for a gift and received:",
      "You traded a shiny pebble for:",
      "You sneezed, the rod jerked, the fish flew. It was:",
      "You slipped on a banana peel on the deck and caught:",
      "You were busy reading this text and caught:",
      "You cast with your non-dominant hand and caught:",
      "You cast with your eyes closed and caught:",
      "You cast while standing on one leg and caught:",
      "You hooked something that smells like old cheese:",
      "You hooked something that smells like victory:",
      "You hooked something that smells like... teen spirit?",
      "You were about to go home empty-handed but caught:",
      "You sighed deeply, the fish heard your pain, and you caught:",
      "You stared into the abyss and the abyss sent back:",
      "You gave up on life for a second and caught:",
      "Calculated. Precision. Skill. You caught:",
      "360 no-scope cast! You caught:",
      "Textbook technique resulted in catching:",
      "Just like in the simulation! You caught:",
      "Frame-perfect input allowed you to catch:",
      "A raindrop hit the water and spooked into your hands:",
      "The sun glared in your eyes and you blindly caught:",
      "A gust of wind blew your line into the mouth of:",
      "It started hailing and you quickly caught:",
      "A stray cat hissed at the water and scared up:",
      "A frog jumped on your reel and helped you catch:",
      "A pelican tried to steal this, but you caught:",
      "A beaver slapped its tail and stunned:",
      "You used a glowing worm and caught:",
      "You used a piece of ancient bread and caught:",
      "You used a shiny Pokemon card and caught:",
      "You accidentally used your credit card as bait and caught:",
      "You promised to name it 'Bob' and caught:",
      "You looked left, cast right, and caught:",
      "You spun around 3 times and cast:",
      "You whispered the Konami code and caught:",
      "You held the rod upside down and caught:",
      "You tried to fish with a spoon and caught:",
      "You tried to fish with a fork and caught:",
      "You tried to fish with a spork and caught:",
      "You cast into the past and caught:",
      "You cast into the future and caught:",
      "The narrator (me) decided you should catch:",
      "The script says you catch:",
      "Error 404: Fish not found... just kidding, you caught:",
      "Buffering... Buffering... You caught:",
      "Loading success! You caught:",
      "Connection established with:",
      "Downloading fish... Complete! You caught:",
      "You rolled the dice and won:",
      "Jackpot! You caught:",
      "Winner winner fish dinner! You caught:"
];