// Funny fishing lines
window.FUNNY_LINES = [
  "You prayed to the ocean gods and caught:",
  "You accidentally farted underwater and caught:",
  "You threw a gold coin for good luck and caught:",
  "You sang a sea shanty terribly and caught:",
  "You told a bad joke to the fish and caught:",
  "Your bait smelled like pizza and you caught:",
  "You sneezed at the perfect moment and caught:",
  "You whispered sweet nothings to the ocean and caught:",
  "You did a little dance on the boat and caught:",
  "Your fishing rod sneezed (yes, really) and caught:",
  "You blinked three times and magically caught:",
  "A seagull judged your technique but you still caught:",
  "You forgot what you were doing and somehow caught:",
  "You yelled 'YOLO!' into the void and caught:",
  "Your hat flew off and startled you into catching:",
  "You dropped your phone (it's waterproof) and caught:",
  "A dolphin gave you a thumbs up and you caught:",
  "You were daydreaming about lunch and caught:",
  "Pure dumb luck blessed you with:",
  "You pretended to be a fish and caught:",
  "Your stomach growled and scared you into catching:",
  "You hummed the Jaws theme and caught:",
  "A fish told you where the others were hiding and you caught:",
  "You looked away for one second and caught:",
  "The fish felt sorry for you and you caught:",
  "You accidentally used the wrong bait but still caught:",
  "Your shadow spooked the fish into your net and you caught:",
  "You were checking your phone and somehow caught:",
  "The universe aligned perfectly and you caught:",
  "You burped underwater (bubbles everywhere!) and caught:"
];