// Theme definitions for Arcane Angler
export const themes = {
  dark: {
    name: 'Dark',
    primary: { from: 'gray-900', via: 'gray-800', to: 'gray-950' },
    primarySolid: 'gray-900',
    secondary: 'gray-800',
    surface: 'gray-950',
    border: 'gray-700',
    borderLight: 'gray-600',
    text: 'white',
    textMuted: 'gray-300',
    textDim: 'gray-400',
    hover: 'gray-800',
    accent: 'yellow-400',
    accentHover: 'yellow-500'
  },
  ocean: {
    name: 'Ocean Blue',
    primary: { from: 'blue-900', via: 'blue-800', to: 'blue-950' },
    primarySolid: 'blue-900',
    secondary: 'blue-800',
    surface: 'blue-950',
    border: 'blue-700',
    borderLight: 'blue-600',
    text: 'white',
    textMuted: 'blue-300',
    textDim: 'blue-400',
    hover: 'blue-800',
    accent: 'yellow-400',
    accentHover: 'yellow-500'
  },
  forest: {
    name: 'Forest Green',
    primary: { from: 'green-900', via: 'green-800', to: 'green-950' },
    primarySolid: 'green-900',
    secondary: 'green-800',
    surface: 'green-950',
    border: 'green-700',
    borderLight: 'green-600',
    text: 'white',
    textMuted: 'green-300',
    textDim: 'green-400',
    hover: 'green-800',
    accent: 'yellow-400',
    accentHover: 'yellow-500'
  },
  sunset: {
    name: 'Sunset Purple',
    primary: { from: 'purple-900', via: 'purple-800', to: 'purple-950' },
    primarySolid: 'purple-900',
    secondary: 'purple-800',
    surface: 'purple-950',
    border: 'purple-700',
    borderLight: 'purple-600',
    text: 'white',
    textMuted: 'purple-300',
    textDim: 'purple-400',
    hover: 'purple-800',
    accent: 'pink-400',
    accentHover: 'pink-500'
  },
  ember: {
    name: 'Warm Ember',
    primary: { from: 'orange-900', via: 'orange-800', to: 'orange-950' },
    primarySolid: 'orange-900',
    secondary: 'orange-800',
    surface: 'orange-950',
    border: 'orange-700',
    borderLight: 'orange-600',
    text: 'white',
    textMuted: 'orange-300',
    textDim: 'orange-400',
    hover: 'orange-800',
    accent: 'yellow-400',
    accentHover: 'yellow-500'
  },
  slate: {
    name: 'Cool Slate',
    primary: { from: 'slate-900', via: 'slate-800', to: 'slate-950' },
    primarySolid: 'slate-900',
    secondary: 'slate-800',
    surface: 'slate-950',
    border: 'slate-700',
    borderLight: 'slate-600',
    text: 'white',
    textMuted: 'slate-300',
    textDim: 'slate-400',
    hover: 'slate-800',
    accent: 'cyan-400',
    accentHover: 'cyan-500'
  }
};

export default themes;
